import { grid, type SpriteDef } from '../format';
import type { ColourRef } from '../palette';

/**
 * Every ability's picture on the action bar (B8, decision 111): what the blow
 * or the spell does, in the colour it is done in, over which the ability's
 * name is written. A second rank is the first's picture.
 *
 * Painted by a generator out of shapes shaded by the style guide's light and
 * pasted in as the pictures it made, as the trees were (decision 109).
 */

function icon(id: string, legend: Readonly<Record<string, ColourRef>>, rows: string): SpriteDef {
  return { id, kind: 'icon', width: 32, height: 32, legend, animations: { still: [grid(rows)] } };
}

export const FIREBALL = icon(
  'icon-fireball',
  {
    b: 'fire.1',
    c: 'fire.2',
    d: 'fire.3',
    e: 'fire.4',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    l: 'yellow.1',
    m: 'yellow.2',
    n: 'yellow.3',
    o: 'yellow.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................jjjjiiii........
    ...............jjjjjiiiih.......
    ..............jjjjjjiiiihh......
    .............jjjjjooonnmhhh.....
    ............jjjjjoooonnmmhhg....
    ............jjjjjooonnnmmhhg....
    ............jjjjionnnnmmlhgg....
    ............iiiiinnnnmmmlhgg....
    ............iiiiinnmmmmllggg....
    ............iiiiimmmmllllggg....
    ............iiiiihllllllgggg....
    ...........dhhhhhhhhhhgggggg....
    ..........ecdhhhhhhhhgggggg.....
    .........ecccdhhhhhggggggg......
    .........dccccdgggggggggg.......
    ........dndccccdgggggggg........
    .......ecdccccccc...............
    ......eccccccccb................
    .....ndccccccbb.................
    ......dcccccbn..................
    ....edcccccb....................
    ....dcccbbb.....................
    ....dccb........................
    ....dbbb........................
    ................................
    ................................
    ................................
    ................................
`,
);

export const MANA_SHIELD = icon(
  'icon-mana-shield',
  {
    b: 'arcane.1',
    c: 'arcane.2',
    d: 'arcane.3',
    e: 'arcane.4',
    g: 'arcane.1',
    n: 'arcane.3',
    o: 'arcane.4',
  },
  `
    ................................
    ................................
    ................................
    ...........bbbbbbbbbb...........
    .........bbbbeeedddbbbb.........
    ........bbeeeggggggdddbb........
    ......bbbeggggggggggggdbbb......
    ......bbeeeggggggggggggcbb......
    .....bbeegggggggogggggggcbb.....
    ....bbegegggggggoggggggggcbb....
    ....beggggggggggogggggggggcb....
    ...bbegggggggdddoddgggggggcbb...
    ...bbegggggnddddodddgnggggbbb...
    ...beggggggdnnddoddnnggggggbb...
    ...bdggggggdddndodnccggggggbb...
    ...bdggggggddddnoncccggggggbb...
    ...bdggggggdddddnccccggggggbb...
    ...bdggggggddddnoncccggggggbb...
    ...bdggggggdddncocnccggggggbb...
    ...bbdggggggnnccoccnngggggbbb...
    ...bbdgggggngcccoccggnggggbbb...
    ....bcggggggggggogggggggggbb....
    ....bbcgggggggggoggggggggbbb....
    .....bbcggggggggogggggggbbb.....
    ......bbcgggggggoggggggbbb......
    ......bbbcggggggggggggbbbb......
    ........bbbbbggggggbbbbb........
    .........bbbbbbbbbbbbbb.........
    ...........bbbbbbbbbb...........
    ................................
    ................................
    ................................
`,
);

export const MEND = icon(
  'icon-mend',
  {
    b: 'nature.1',
    c: 'nature.2',
    d: 'nature.3',
    e: 'nature.4',
    i: 'nature.3',
    j: 'nature.4',
    o: 'nature.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ...........................o....
    ................................
    .....o.......eedddd.............
    ...........eeeeeddddc...........
    ..........eeeejjjjjddc..........
    .........eeeeejiiijddcc.........
    ........eeeeeejiiijddccc........
    .......eeeeeeejiiijddcccb.......
    .......eeeeeeejiiijdccccb...o...
    .......eeeeeedjiiijdccccb.......
    ......deeeeeddjiiijcccccbb......
    ......djjjjjjjjiiijjjjjjjj......
    ......djiiiiiiiiiiiiiiiiij......
    ......djiiiiiiiiiiiiiiiiij......
    ......djiiiiiiiiiiiiiiiiij......
    ......djjjjjjjjiiijjjjjjjj......
    .......dddddccjiiijcbbbbb.......
    .......cccccccjiiijbbbbbb.......
    .......cccccccjiiijbbbbbb.......
    ........ccccccjiiijbbbbb........
    .........cccccjiiijbbbb.........
    ..........bbbbjiiijbbb..........
    ...........bbbjjjjjbb.....o.....
    ....o........bbbbbb.............
    ................................
    ................................
    ................................
    ................................
`,
);

export const FIRESTORM = icon(
  'icon-firestorm',
  {
    b: 'fire.1',
    c: 'fire.2',
    d: 'fire.3',
    e: 'fire.4',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    l: 'fire.1',
    m: 'fire.2',
    n: 'fire.3',
    o: 'fire.4',
    q: 'yellow.1',
    r: 'yellow.2',
    s: 'yellow.3',
    t: 'yellow.4',
  },
  `
    ................................
    .............ed.................
    .....ed......db.................
    .....db......dcd.....ed.........
    .....dcd......db.....db.........
    ......db......dcd....dcd........
    ......dcd......db.....db........
    .......db......dcd....dcd.......
    .......dcd.....dcb.....db.......
    .......dcb......db.....dcd......
    ........db......dcd....dcb......
    ........dcd......db.....db......
    .........db......dbih...dcd.....
    .........dbii.....hhhh...db.....
    ..........iiii...hhhhhh..dbgg...
    .........iiiiii..hhhhhh...gggg..
    .........iiiihh...hhhh...gggggg.
    ..........hhhh.....hh....gggggg.
    ...........hh.............gggg..
    ..................on.......gg...
    ..................nl............
    .................omln...........
    .......on.......omlsn...........
    ......oml.....onmltqnnn....on...
    .....ollsn....nmltrrsnmn..oll...
    ...onltsqnnn.ommlsrrqnmmnnltsn..
    ...nmlsrrsnmnmmmlsrrrsnmmmlsqnn.
    ...nmlsrrrsnmmmltrrrrqnmmmlsrsn.
    ...nllsqqqqnllllsqqqqqnlllsqqqm.
    ................................
    ................................
    ................................
`,
);

export const POWER_SLASH = icon(
  'icon-power-slash',
  {
    c: 'spray.2',
    d: 'spray.3',
    e: 'spray.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    m: 'gold.2',
    n: 'gold.3',
    q: 'leather.1',
    r: 'leather.2',
    s: 'leather.3',
    t: 'leather.4',
  },
  `
    ................................
    ................................
    ......eeeee.....................
    ......eeeeeeee..................
    ......dddddddeeee...............
    ......cccccddddeee..............
    ......ccccccccdddeee............
    ..........ccccccdddee...........
    .............cccccddee..........
    ...............ccccddee.........
    .................cccjiee........
    ..................jihgdee.......
    .................jhhgcddee......
    ................jhhhgccdde......
    ...............jhhhg.cccdee.....
    ..............jhhhg...ccddee....
    .............jhhhg....cccdee....
    ............jhhhg......ccdde....
    ...........jhhhg.......cccdee...
    ......nn..jhhhg.........ccdde...
    .......nnihhhg..........ccdde...
    ........nnihg...........cccdee..
    ........snnh.............ccdee..
    .......trrnn.............ccdee..
    ......trq..nn............ccdee..
    .....srq....m...................
    ......r.........................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const BATTLE_FURY = icon(
  'icon-battle-fury',
  {
    b: 'blood.1',
    c: 'blood.2',
    d: 'blood.3',
    e: 'blood.4',
    g: 'skin.1',
    h: 'skin.2',
    i: 'skin.3',
    j: 'skin.4',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ...............dd...............
    ...............dd...............
    ........ee.....ed.....cc........
    ........eee....ed....ddc........
    .........ee....ed....dd.........
    .........eee...ed...ddd.........
    ..........ee.eeeddd.dd..........
    ...ee.....eeeeeddddddd.....bb...
    ...deee...jiiiiiiiiiiii..ccbb...
    ....eeeeeeijhhjhhjhhjhgccccb....
    ......eeeeihhhhhhhhhhhgccc......
    ........eeihghhghhghhggc........
    .......eeeihghhghhghhggcc.......
    .......ddjhhhhhhhhhhhhgcc.......
    .ddddddddihhhhhhhhhhhhgccbbbbbb.
    .ddddddddihhhhhhhhhhhhgccbbbbbb.
    .......ddihhhhhhhhhhhhgcb.......
    .......ddihhhhhhhhhhhhgbb.......
    ........ddiggggggggggggb........
    ......ddddhonnnnnnnnnnhbbb......
    ....cccccccnmmmmmmmmmlbbbbbb....
    ...cccc...cnmmmmmmmmml...bbbb...
    ...cc.....cnmmmmmmmmml.....bb...
    ..........cnmmmmmmmmml..........
    .........ccnllllllllllb.........
    .........bb....bb....bb.........
    ........bbb....bb....bbb........
    ........bb.....bb.....bb........
    ...............bb...............
    ...............bb...............
    ................................
`,
);

export const SECOND_WIND = icon(
  'icon-second-wind',
  {
    b: 'spray.1',
    c: 'spray.2',
    d: 'spray.3',
    e: 'spray.4',
    g: 'red.1',
    h: 'red.2',
    i: 'red.3',
    j: 'red.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...........eddddddd.............
    ...ddddddddcbbbbbbcdd...........
    ........dcbb......dbcd....ed....
    .......ecb..........dcd...dcd...
    ......ecb...........dcb....db...
    ......db.............dcd...db...
    ......db......i..ji...db...db...
    .....ecb...ecjhiihhi..db...dcd..
    .....db....dihhhhhhg..db....db..
    .....db....ddihhhhhg..db...ecb..
    .....db....db.ihhhg..ecb...db...
    .....dcd...dcd.ihg...db....db...
    .....dcb...dcb.ig...ecb....db...
    ......db....dcddddddcb....ecb...
    ......dcd....dbcccbbb.....db....
    ......dccd.....dbb.......ecb....
    .......dcb.............edcb.....
    ........dcdd..........eccb......
    .........dccdd......edccb.......
    ..........dbbcddddddcccb........
    .............dbbbbbbbbddddddddd.
    ................................
    ................................
    ................................
    ................................
`,
);

export const CRUSHING_BLOW = icon(
  'icon-crushing-blow',
  {
    d: 'yellow.3',
    g: 'wood.1',
    h: 'wood.2',
    i: 'wood.3',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
    o: 'metal.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    .................o..............
    ................omn.............
    ...............ommmni...........
    ..............ommmmmni..........
    .............ommmmmmmni.........
    ............ommmmmmmmmni........
    ...........olmmmmmmmmmmni.......
    .............nmmmmmmmmmlii......
    .............dnmmmmmmml.ihi.....
    .............ddnmmmmml...ihi....
    .............dd.nmmml.....ihi...
    ............ddd..nml.......ihi..
    .......dd...ddd...m.........ig..
    .......ddd..dd...dd.............
    .d......ddddddddddd.............
    .ddddddddddddddddd..............
    .dddddddddddddddd...............
    .......dddddddddddddddd.........
    ......ddddddddddddddddddd.......
    .....ddddddddddd......ddd.......
    .....dd...dd..ddd...............
    .........ddd...dd...............
    .........ddd....................
    .........dd.....................
    .........dd.....................
    .........dd.....................
    ................................
`,
);

export const AIMED_SHOT = icon(
  'icon-aimed-shot',
  {
    b: 'red.1',
    d: 'red.3',
    j: 'yellow.4',
    n: 'thatch.3',
    q: 'metal.1',
    r: 'metal.2',
    s: 'metal.3',
    w: 'bone.2',
    x: 'bone.3',
  },
  `
    ................................
    ................................
    ................bbbbbb..........
    .............bbbbbbbbbbbb.......
    ............bbbbbbbbbbbbbb......
    ...........bbbbddddddddbbbb.....
    ..........bbbbddddddddddbbbb....
    .........bbbbdddddbbdddddbbbb...
    .........bbbddddbbbbbbddddbbb...
    .........bbddddbbbbbbbbddddbb...
    ........bbbdddbbbbddbbbbdddbbb..
    ........bbbdddbbbjjjjbbbdddbbb..
    ........bbbddbbbdjjjjdbbbddbbb..
    ........bbbddbbbsssjjdbbbddbbb..
    ........bbbdddbbbsqjjbbbdddbbb..
    ........bbbdddbbbnrdbbbbdddbbb..
    .........bbddddbnbbbbbbddddbb...
    .........bbbdddnbbbbbbddddbbb...
    .........bbbbdndddbbdddddbbbb...
    ..........bbbnddddddddddbbbb....
    ...........bnbbddddddddbbbb.....
    ...........nbbbbbbbbbbbbbb......
    ..........n..bbbbbbbbbbbb.......
    .........n......bbbbbb..........
    ........n.......................
    .......n........................
    ......n.........................
    ....xn..........................
    ..xwnx..........................
    ...nx...........................
    ....w...........................
    ................................
`,
);

export const RAPID_FIRE = icon(
  'icon-rapid-fire',
  {
    c: 'thatch.2',
    d: 'thatch.3',
    e: 'thatch.4',
    g: 'metal.1',
    i: 'metal.3',
    m: 'bone.2',
    n: 'bone.3',
    o: 'bone.4',
    r: 'spray.2',
    s: 'spray.3',
  },
  `
    ................................
    ................................
    ................................
    ........................iii.....
    .........................ig.....
    .........................ig.....
    .......................dc.......
    ......................d.........
    ....................dc..........
    ..................dc............
    .................d..............
    ...............dc..........iii..
    ..............d.............ig..
    .............d..............ig..
    ...........dc.............dc....
    ......sr..d.............dc......
    .....s..dc............dc........
    ...sr..d............dc..........
    ...n.dc...........dc............
    .nmdc...........ec..............
    ..dom...........c.........ii....
    ...m..........dc...........ii...
    ............dc............dig...
    ....sr....dc............dc......
    ...s....dc...........ddc........
    .sr.n.dc..........ddc...........
    ...ndc...........d..............
    ...dnm....sr..ddc...............
    ...n....ns.ddc..................
    .......srdc.....................
    .......dcn......................
    ................................
`,
);

export const FIELD_DRESSING = icon(
  'icon-field-dressing',
  {
    b: 'linen.1',
    c: 'linen.2',
    d: 'linen.3',
    e: 'linen.4',
    g: 'linen.1',
    h: 'linen.2',
    i: 'linen.3',
    j: 'linen.4',
    o: 'linen.4',
    q: 'red.1',
    r: 'red.2',
    s: 'red.3',
    t: 'red.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ............i...................
    ......iiihoooooiiih.............
    ....jhoooooooooooooii...........
    ....ioooooooooooooooii..........
    ....iiooooooooooooojhg..........
    ....ihiiiiooooojiiihhg..........
    ....ihhhhhisssrihhhhhg..........
    ....ihhhhhhhhhhhhhhhhg..........
    ....ihhhgggtsssigghhhg..........
    ....ihhgtssrrrrsssihhg..........
    ....ihhgsrrrrrrrrqihhg....d.....
    ....ihhgsrrrrrrrrqihhg..edb.....
    ....ihhgsqqqqqqqqqihhgedccb.....
    ....ihhhhhhhhhhhhhhhhgdcccb.....
    ....ihhhhhgtsssihhhhhgdcccb.....
    ....ihhhhhgsqqqihhhhhgdcccb.....
    ....ihhhhhhiiiihhhhhhgdcccb.....
    ....ihhhhhhhhhhhhhhhggdcbb......
    .....igghhhhhhhhhgggedbb........
    ........iggggggggeddbb..........
    ..........dddddddbbb............
    ...........dcccbb...............
    ...........dcbb.................
    ............c...................
    ................................
    ................................
    ................................
    ................................
`,
);

export const PIERCING_SHOT = icon(
  'icon-piercing-shot',
  {
    E: 'yellow.4',
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    f: 'ink.0',
    m: 'thatch.2',
    n: 'thatch.3',
    q: 'metal.1',
    s: 'metal.3',
    w: 'bone.2',
    x: 'bone.3',
    y: 'bone.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    .............d..................
    .............ddd...........sss..
    .............dccdd..........sq..
    .............dccccdd........sq..
    .............dccccccd.....nm....
    .............dccccccb....n......
    .............dccccccb..nm.......
    .............dccccccb.nE........
    .............dcccccbnm..........
    .............dccbbbnd.E.........
    .............dcbfnmeb...E.......
    .............dbfnffdb...........
    .............dbnffecb...........
    .............cneddccb...........
    ...........Enmecccccb...........
    ...........n.eccccccb...........
    .........nm..dccccccb...........
    ........n.E..dccccccb...........
    ......nm.....dccccccb...........
    ...x.n........dbccccb...........
    .xwnm...........dbccb...........
    ..nyw.............dbb...........
    ...w................c...........
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);
