import { flipped, grid, type SpriteDef } from '../format';

/**
 * What stands in a room (decision 109), the 3D fittings drawn: shelves, a
 * hearth, a bench, crates and a bed, set against the walls `art/rooms.ts`
 * says, and the counter whoever works there is served across. None of them
 * blocks anybody, which is the room's arithmetic (`docs/architecture/
 * buildings.md`); a side wall's fitting is drawn along its length, so a bench
 * against the back wall and one against a side are two drawings.
 */

const SHELVES_STILL = grid(`
  ................................................................
  ................................................................
  .........zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.........
  .........yxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyywv.........
  .........yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxvwtttvwtttvwwwwvwwwwxwwwwppwwwvGwwwvwwwwvwwv.........
  .........yxvtuuutwtuutwwGwvMwwwxwwwpqqpwwGHGwwvtttwvwwv.........
  .........yxvtuttstuutswGHGNOMwwxwwwoppqwwGHGwwtuutwvwwv.........
  .........yxvstssssttsswGHGNOMwwxwwwopppwwGGGwwtttswvwwv.........
  .........yxvwsssvwsssvwGGGMNMwwxwwwwoowwwvwwwwvsswwvwwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxyyyyyyyyyyyyyyyyyyyyxwyyyyyyyyyyyyyyyyyyyywv.........
  .........yxxxxxxxxxxxxxxxxxxxxxxwxxxxxxxxxxxxxxxxxxxxwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxvwpqpvwwzyyyyywvwwwwxwwwwvwwwwvwwwwvMMwwvwwv.........
  .........yxvpqqqpwwyxxxxwwvwwwwxwwwwtttwwpqpwwMNOMwvwwv.........
  .........yxvopqqpowyxwxxwwvwwwwxwwwtuuutwpqqpwMNNMwvwwv.........
  .........yxvoppppowyxxxxwwvwwwwxwwwtttttwoppowvMMwwvwwv.........
  .........yxvwoooowwwwwwwvwvwwwwxwwwwssswwooowwvwwwwvwwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxyyyyyyyyyyyyyyyyyyyyxwyyyyyyyyyyyyyyyyyyyywv.........
  .........yxxxxxxxxxxxxxxxxxxxxxxwxxxxxxxxxxxxxxxxxxxxwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxvwGGGvHHHwvwwwwvwwwwxwwwwxyyyxvwtttvwwwwvwwv.........
  .........yxvGHHHGIIIHvwwwwvwwwwxwwwxyzyzyxwuuuvwwwwvwwv.........
  .........yxvGHHHGIIIHvwwwwvwwwwxwwwxyyyyyxwtttvwwwwvwwv.........
  .........yxvwFFFvGGGwvwwwwvwwwwxwwwwxxxxxvwsssvwwwwvwwv.........
  .........yxvwwwwvwwwwvwwwwvwwwwxwwwwvwwwwvwwwwvwwwwvwwv.........
  .........yxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyywv.........
  ................................................................
  ................................................................
`);

/**
 * Uprights with boards across and what a store keeps on them (jars, bottles,
 * sacks, a crate, cloth), long enough to show either side of whoever stands in
 * front of them.
 */
export const SHELVES: SpriteDef = {
  id: 'shelves',
  kind: 'prop',
  width: 64,
  height: 32,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    M: 'metal.0',
    N: 'metal.1',
    O: 'metal.2',
    o: 'ochre.1',
    p: 'ochre.2',
    q: 'ochre.3',
    s: 'linen.2',
    t: 'linen.3',
    u: 'linen.4',
    F: 'crimson.0',
    G: 'crimson.1',
    H: 'crimson.2',
    I: 'crimson.3',
  },
  animations: { still: [SHELVES_STILL] },
};

const HEARTH_LOOP_0 = grid(`
  ................................
  ................................
  ................................
  .......DDDDDDBCDDDDDBCDDB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DBCDDDDDBCDDDDDBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDBCDDDDDBCDDDDDB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDDDBCDDDDDBCDDDB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DCDDMMDBCDDDDDBCDB.......
  .......DCCMNOMBCCCCCCBCCB.......
  .......DCCMNNMBCCCCCCBCCB.......
  ....zzzzzzzzzzzzzzzzzzzzzzzz....
  ....yyyyyyyyyyyyyyyyyyyyyyyy....
  ....wwwwwwwwwwwwwwwwwwwwwwww....
  .....DDDDDBCDDDDDBCDDDDDBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....BBBBBAAAAAAAAAAAABBBBB.....
  .....BCDDkkkkkkkkkkkkkkDDDB.....
  .....BCCCkkkkkkhkkkkkkkCCCB.....
  .....BCCCkkkkkhhkkkkkkkCCCB.....
  .....BBBBkkkkkhihkkkkkkBBBB.....
  .....DDBCkkkkhiihkkhkkkDDDB.....
  .....CCBCkkkhhijihkhhkkCCCB.....
  .....CCBCkkhhijjjihhhkkCCCB.....
  .....BBBBkkhijjjjjiihkkBBBB.....
  .....DDDDkhhijjjjjjihkkBCDB.....
  .....CCCCkhiijjjjjiihhkBCCB.....
  .....CCCCkhiijjjjjjiihkBCCB.....
  .....BBBBkghiiijjjiihgkBBBB.....
  .....CDDDkkghiiiiiihgkkDDBB.....
  .....CCCCkkxxxxxxxxxxkkCCBB.....
  .....CCCCkkwwwwwwwwwwkkCCBB.....
  .....BBBBkllllllllllllkBBBB.....
  .....AAAAAAAAAAAAAAAAAAAAAA.....
  ................................
  ................................
`);

const HEARTH_LOOP_1 = grid(`
  ................................
  ................................
  ................................
  .......DDDDDDBCDDDDDBCDDB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DBCDDDDDBCDDDDDBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDBCDDDDDBCDDDDDB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDDDBCDDDDDBCDDDB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DCDDMMDBCDDDDDBCDB.......
  .......DCCMNOMBCCCCCCBCCB.......
  .......DCCMNNMBCCCCCCBCCB.......
  ....zzzzzzzzzzzzzzzzzzzzzzzz....
  ....yyyyyyyyyyyyyyyyyyyyyyyy....
  ....wwwwwwwwwwwwwwwwwwwwwwww....
  .....DDDDDBCDDDDDBCDDDDDBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....BBBBBAAAAAAAAAAAABBBBB.....
  .....BCDDkkkkkkkkkkkkkkDDDB.....
  .....BCCCkkkkkkkkhkkkkkCCCB.....
  .....BCCCkkkkkkkhhkkkkkCCCB.....
  .....BBBBkhkkkkhihkkkkkBBBB.....
  .....DDBCkhhkkkhiihkkkkDDDB.....
  .....CCBCkhihkhhijhhkkkCCCB.....
  .....CCBCkkhihhijjihkkkCCCB.....
  .....BBBBkkhiiijjjiihkkBBBB.....
  .....DDDDkhhiijjjjjihkkBCDB.....
  .....CCCCkhiijjjjjjihhkBCCB.....
  .....CCCCkhiijjjjjjiihkBCCB.....
  .....BBBBkghiiijjjiihgkBBBB.....
  .....CDDDkkghiiiiiihgkkDDBB.....
  .....CCCCkkxxxxxxxxxxkkCCBB.....
  .....CCCCkkwwwwwwwwwwkkCCBB.....
  .....BBBBkllllllllllllkBBBB.....
  .....AAAAAAAAAAAAAAAAAAAAAA.....
  ................................
  ................................
`);

const HEARTH_LOOP_2 = grid(`
  ................................
  ................................
  ................................
  .......DDDDDDBCDDDDDBCDDB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DBCDDDDDBCDDDDDBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDBCDDDDDBCDDDDDB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDDDBCDDDDDBCDDDB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DCDDMMDBCDDDDDBCDB.......
  .......DCCMNOMBCCCCCCBCCB.......
  .......DCCMNNMBCCCCCCBCCB.......
  ....zzzzzzzzzzzzzzzzzzzzzzzz....
  ....yyyyyyyyyyyyyyyyyyyyyyyy....
  ....wwwwwwwwwwwwwwwwwwwwwwww....
  .....DDDDDBCDDDDDBCDDDDDBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....BBBBBAAAAAAAAAAAABBBBB.....
  .....BCDDkkkkkkkkkkkkkkDDDB.....
  .....BCCCkkkkkkkhkkkkkkCCCB.....
  .....BCCCkkkkkkhhkkkkkkCCCB.....
  .....BBBBkkkkkkhihkkkkkBBBB.....
  .....DDBCkhkkkhiihkkkkkDDDB.....
  .....CCBCkhhkhhijihkkkkCCCB.....
  .....CCBCkkhhhijjjihkhkCCCB.....
  .....BBBBkkhiijjjjjhhhkBBBB.....
  .....DDDDkhhiijjjjjiihkBCDB.....
  .....CCCCkhiijjjjjjiihkBCCB.....
  .....CCCCkhiijjjjjjiihkBCCB.....
  .....BBBBkghiiijjjiihgkBBBB.....
  .....CDDDkkghiiiiiihgkkDDBB.....
  .....CCCCkkxxxxxxxxxxkkCCBB.....
  .....CCCCkkwwwwwwwwwwkkCCBB.....
  .....BBBBkllllllllllllkBBBB.....
  .....AAAAAAAAAAAAAAAAAAAAAA.....
  ................................
  ................................
`);

const HEARTH_LOOP_3 = grid(`
  ................................
  ................................
  ................................
  .......DDDDDDBCDDDDDBCDDB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DCCCCCBCCCCCCBCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DBCDDDDDBCDDDDDBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBCCCCCCBCCCCCCBCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDBCDDDDDBCDDDDDB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DCCBCCCCCCBCCCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DDDDDBCDDDDDBCDDDB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DCCCCBCCCCCCBCCCCB.......
  .......DBBBBBBBBBBBBBBBBB.......
  .......DCDDMMDBCDDDDDBCDB.......
  .......DCCMNOMBCCCCCCBCCB.......
  .......DCCMNNMBCCCCCCBCCB.......
  ....zzzzzzzzzzzzzzzzzzzzzzzz....
  ....yyyyyyyyyyyyyyyyyyyyyyyy....
  ....wwwwwwwwwwwwwwwwwwwwwwww....
  .....DDDDDBCDDDDDBCDDDDDBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....CCCCCBCCCCCCBCCCCCCBCB.....
  .....BBBBBAAAAAAAAAAAABBBBB.....
  .....BCDDkkkkkkkkkkkkkkDDDB.....
  .....BCCCkkkkkhkkkkkkkkCCCB.....
  .....BCCCkkkkkhhkkkkkkkCCCB.....
  .....BBBBkkkkhihkkkkhkkBBBB.....
  .....DDBCkkkkhiihkkkhhkDDDB.....
  .....CCBCkkkhhijihhkhhkCCCB.....
  .....CCBCkkhhijjjiihhkkCCCB.....
  .....BBBBkkhijjjjjiihkkBBBB.....
  .....DDDDkhhijjjjjjihkkBCDB.....
  .....CCCCkhiijjjjjiihhkBCCB.....
  .....CCCCkhiijjjjjjiihkBCCB.....
  .....BBBBkghiiijjjiihgkBBBB.....
  .....CDDDkkghiiiiiihgkkDDBB.....
  .....CCCCkkxxxxxxxxxxkkCCBB.....
  .....CCCCkkwwwwwwwwwwkkCCBB.....
  .....BBBBkllllllllllllkBBBB.....
  .....AAAAAAAAAAAAAAAAAAAAAA.....
  ................................
  ................................
`);

/** A fireplace built into the back wall: a chimney breast up it, a mantel with a pot on it, a fire. */
export const HEARTH: SpriteDef = {
  id: 'hearth',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    A: 'masonry.0',
    B: 'masonry.1',
    C: 'masonry.2',
    D: 'masonry.3',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    M: 'metal.0',
    N: 'metal.1',
    O: 'metal.2',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    k: 'ink.0',
    l: 'ink.1',
  },
  animations: { loop: [HEARTH_LOOP_0, HEARTH_LOOP_1, HEARTH_LOOP_2, HEARTH_LOOP_3] },
};

const HEARTH_EAST_LOOP_0 = grid(`
  ................................
  ................................
  ................................
  ................................
  .............EEEEEEEEE..........
  .............ECCCCCBCB..........
  .............ECCCCCBCB..........
  .............EBBBBBBBB..........
  .............EBCDDDDDB..........
  .............EBCCCCCCB..........
  .............EBCCCCCCB..........
  .............EBBBBBBBB..........
  .............EDDBCDDDB..........
  .............ECCBCCCCB..........
  .............ECCBCCCCB..........
  .............EBBBBBBBB..........
  .............EDDDDBCDB..........
  .............ECCCCBCCB..........
  .............ECCCCBCCB..........
  .............EBBBBBBBB..........
  .............ECDDDDDBB..........
  .............ECCCCCCBB..........
  .............ECCCCCCBB..........
  .............EBBBBBBBB..........
  .............EDBCDDDDB..........
  .............ECBMMCCCB..........
  .............ECBNMCCCB..........
  .............EBBBBBBBB..........
  .........EEEEEEEEEEEEB..........
  .........DCCCCCCBCCCCB..........
  .........DCCCCCCBCCCCB..........
  .........DBBBBBBBBBBBB..........
  .........kkkkkADDDBCDB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkABBBBBBB..........
  .........kkkkkADDDDDBB..........
  .........kkhkkACCCCCBB..........
  .........khihkACCCCCBB..........
  .........khijhABBBBBBB..........
  .........khijhABCDDDDB..........
  .........khiihABCCCCCB..........
  .........kghigABCCCCCB..........
  .........kxxxxABBBBBBB..........
  .........kllllADDBCDDB..........
  .........AAAAAAAAAAAAA..........
  ................................
  ................................
`);

const HEARTH_EAST_LOOP_1 = grid(`
  ................................
  ................................
  ................................
  ................................
  .............EEEEEEEEE..........
  .............ECCCCCBCB..........
  .............ECCCCCBCB..........
  .............EBBBBBBBB..........
  .............EBCDDDDDB..........
  .............EBCCCCCCB..........
  .............EBCCCCCCB..........
  .............EBBBBBBBB..........
  .............EDDBCDDDB..........
  .............ECCBCCCCB..........
  .............ECCBCCCCB..........
  .............EBBBBBBBB..........
  .............EDDDDBCDB..........
  .............ECCCCBCCB..........
  .............ECCCCBCCB..........
  .............EBBBBBBBB..........
  .............ECDDDDDBB..........
  .............ECCCCCCBB..........
  .............ECCCCCCBB..........
  .............EBBBBBBBB..........
  .............EDBCDDDDB..........
  .............ECBMMCCCB..........
  .............ECBNMCCCB..........
  .............EBBBBBBBB..........
  .........EEEEEEEEEEEEB..........
  .........DCCCCCCBCCCCB..........
  .........DCCCCCCBCCCCB..........
  .........DBBBBBBBBBBBB..........
  .........kkkkkADDDBCDB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkABBBBBBB..........
  .........kkkkkADDDDDBB..........
  .........kkkhkACCCCCBB..........
  .........kkhihACCCCCBB..........
  .........khijhABBBBBBB..........
  .........khijhABCDDDDB..........
  .........khiihABCCCCCB..........
  .........kghigABCCCCCB..........
  .........kxxxxABBBBBBB..........
  .........kllllADDBCDDB..........
  .........AAAAAAAAAAAAA..........
  ................................
  ................................
`);

const HEARTH_EAST_LOOP_2 = grid(`
  ................................
  ................................
  ................................
  ................................
  .............EEEEEEEEE..........
  .............ECCCCCBCB..........
  .............ECCCCCBCB..........
  .............EBBBBBBBB..........
  .............EBCDDDDDB..........
  .............EBCCCCCCB..........
  .............EBCCCCCCB..........
  .............EBBBBBBBB..........
  .............EDDBCDDDB..........
  .............ECCBCCCCB..........
  .............ECCBCCCCB..........
  .............EBBBBBBBB..........
  .............EDDDDBCDB..........
  .............ECCCCBCCB..........
  .............ECCCCBCCB..........
  .............EBBBBBBBB..........
  .............ECDDDDDBB..........
  .............ECCCCCCBB..........
  .............ECCCCCCBB..........
  .............EBBBBBBBB..........
  .............EDBCDDDDB..........
  .............ECBMMCCCB..........
  .............ECBNMCCCB..........
  .............EBBBBBBBB..........
  .........EEEEEEEEEEEEB..........
  .........DCCCCCCBCCCCB..........
  .........DCCCCCCBCCCCB..........
  .........DBBBBBBBBBBBB..........
  .........kkkkkADDDBCDB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkABBBBBBB..........
  .........kkkkkADDDDDBB..........
  .........kkhkkACCCCCBB..........
  .........khhkkACCCCCBB..........
  .........khiihABBBBBBB..........
  .........khijhABCDDDDB..........
  .........khijhABCCCCCB..........
  .........kghhgABCCCCCB..........
  .........kxxxxABBBBBBB..........
  .........kllllADDBCDDB..........
  .........AAAAAAAAAAAAA..........
  ................................
  ................................
`);

const HEARTH_EAST_LOOP_3 = grid(`
  ................................
  ................................
  ................................
  ................................
  .............EEEEEEEEE..........
  .............ECCCCCBCB..........
  .............ECCCCCBCB..........
  .............EBBBBBBBB..........
  .............EBCDDDDDB..........
  .............EBCCCCCCB..........
  .............EBCCCCCCB..........
  .............EBBBBBBBB..........
  .............EDDBCDDDB..........
  .............ECCBCCCCB..........
  .............ECCBCCCCB..........
  .............EBBBBBBBB..........
  .............EDDDDBCDB..........
  .............ECCCCBCCB..........
  .............ECCCCBCCB..........
  .............EBBBBBBBB..........
  .............ECDDDDDBB..........
  .............ECCCCCCBB..........
  .............ECCCCCCBB..........
  .............EBBBBBBBB..........
  .............EDBCDDDDB..........
  .............ECBMMCCCB..........
  .............ECBNMCCCB..........
  .............EBBBBBBBB..........
  .........EEEEEEEEEEEEB..........
  .........DCCCCCCBCCCCB..........
  .........DCCCCCCBCCCCB..........
  .........DBBBBBBBBBBBB..........
  .........kkkkkADDDBCDB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkACCCBCCB..........
  .........kkkkkABBBBBBB..........
  .........kkkkkADDDDDBB..........
  .........khkkkACCCCCBB..........
  .........khihkACCCCCBB..........
  .........khiihABBBBBBB..........
  .........khijhABCDDDDB..........
  .........khiihABCCCCCB..........
  .........kghigABCCCCCB..........
  .........kxxxxABBBBBBB..........
  .........kllllADDBCDDB..........
  .........AAAAAAAAAAAAA..........
  ................................
  ................................
`);

/**
 * The same fireplace against an east wall, seen along it: the breast up the
 * wall lit down its west face, and the fire in a mouth on the side facing the
 * room.
 */
export const HEARTH_EAST: SpriteDef = {
  id: 'hearth-east',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    A: 'masonry.0',
    B: 'masonry.1',
    C: 'masonry.2',
    D: 'masonry.3',
    E: 'masonry.4',
    x: 'wood.2',
    M: 'metal.0',
    N: 'metal.1',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    k: 'ink.0',
    l: 'ink.1',
  },
  animations: {
    loop: [HEARTH_EAST_LOOP_0, HEARTH_EAST_LOOP_1, HEARTH_EAST_LOOP_2, HEARTH_EAST_LOOP_3],
  },
};

/** Against a west wall: the east one turned round, its mouth facing the room from the other side. */
export const HEARTH_WEST: SpriteDef = {
  ...HEARTH_EAST,
  id: 'hearth-west',
  animations: {
    loop: [HEARTH_EAST_LOOP_0, HEARTH_EAST_LOOP_1, HEARTH_EAST_LOOP_2, HEARTH_EAST_LOOP_3].map(
      flipped,
    ),
  },
};

const HEARTH_LOW_LOOP_0 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...............h................
  ..............hh................
  ..............hih...............
  .............hiih..h............
  ............hhijih.hh...........
  ...........hhijjjihhh...........
  ...........hijjjjjiih...........
  ..........hhijjjjjjih...........
  ..........hiijjjjjiihh..........
  ....EEEEEEhiijjjjjjiihEEEEEB....
  ....EDDDDDghiiijjjiihgDDDDDB....
  ....EDDDkkkghiiiiiihgkkkDDDB....
  ....EDDDkxxxxxxxxxxxxxxkDDDB....
  ....EDDDkwwwwwwwwwwwwwwkDDDB....
  ....EDDDDDDDDDDDDDDDDDDDDDDB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....BBBBBBBBBBBBBBBBBBBBBBBB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ................................
  ................................
`);

const HEARTH_LOW_LOOP_1 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .................h..............
  ................hh..............
  ..........h....hih..............
  ..........hh...hiih.............
  ..........hih.hhijhh............
  ...........hihhijjih............
  ...........hiiijjjiih...........
  ..........hhiijjjjjih...........
  ..........hiijjjjjjihh..........
  ....EEEEEEhiijjjjjjiihEEEEEB....
  ....EDDDDDghiiijjjiihgDDDDDB....
  ....EDDDkkkghiiiiiihgkkkDDDB....
  ....EDDDkxxxxxxxxxxxxxxkDDDB....
  ....EDDDkwwwwwwwwwwwwwwkDDDB....
  ....EDDDDDDDDDDDDDDDDDDDDDDB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....BBBBBBBBBBBBBBBBBBBBBBBB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ................................
  ................................
`);

const HEARTH_LOW_LOOP_2 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................h...............
  ...............hh...............
  ...............hih..............
  ..........h...hiih..............
  ..........hh.hhijih.............
  ...........hhhijjjih.h..........
  ...........hiijjjjjhhh..........
  ..........hhiijjjjjiih..........
  ..........hiijjjjjjiih..........
  ....EEEEEEhiijjjjjjiihEEEEEB....
  ....EDDDDDghiiijjjiihgDDDDDB....
  ....EDDDkkkghiiiiiihgkkkDDDB....
  ....EDDDkxxxxxxxxxxxxxxkDDDB....
  ....EDDDkwwwwwwwwwwwwwwkDDDB....
  ....EDDDDDDDDDDDDDDDDDDDDDDB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....BBBBBBBBBBBBBBBBBBBBBBBB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ................................
  ................................
`);

const HEARTH_LOW_LOOP_3 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..............h.................
  ..............hh................
  .............hih....h...........
  .............hiih...hh..........
  ............hhijihh.hh..........
  ...........hhijjjiihh...........
  ...........hijjjjjiih...........
  ..........hhijjjjjjih...........
  ..........hiijjjjjiihh..........
  ....EEEEEEhiijjjjjjiihEEEEEB....
  ....EDDDDDghiiijjjiihgDDDDDB....
  ....EDDDkkkghiiiiiihgkkkDDDB....
  ....EDDDkxxxxxxxxxxxxxxkDDDB....
  ....EDDDkwwwwwwwwwwwwwwkDDDB....
  ....EDDDDDDDDDDDDDDDDDDDDDDB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....CCCCBCCCCCCBCCCCCCBCCCCB....
  ....BBBBBBBBBBBBBBBBBBBBBBBB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....CCCCCCBCCCCCCBCCCCCCBCCB....
  ....AAAAAAAAAAAAAAAAAAAAAAAA....
  ................................
  ................................
`);

/**
 * A hearth against the south wall, which the cutaway takes away with the
 * chimney that goes up it: the raised stone the fire burns on, seen from the
 * room, where the whole fireplace would stand across it in front of whoever
 * is inside.
 */
export const HEARTH_LOW: SpriteDef = {
  id: 'hearth-low',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    A: 'masonry.0',
    B: 'masonry.1',
    C: 'masonry.2',
    D: 'masonry.3',
    E: 'masonry.4',
    w: 'wood.1',
    x: 'wood.2',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    k: 'ink.0',
  },
  animations: {
    loop: [HEARTH_LOW_LOOP_0, HEARTH_LOW_LOOP_1, HEARTH_LOW_LOOP_2, HEARTH_LOW_LOOP_3],
  },
};

const BENCH_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...zzzzzzzzzzzzzzzzzzzzzzzzzz...
  ...yyyyyyyxyyyyyyxyyyyyxyyyyy...
  ...yyyyyyyxyyyyyyxyyyyyxyyyyy...
  ...yyyyyyyxyyyyyyxyyyyyxyyyyy...
  ...yyyyyyyyyyyyyyyyyyyyyyyyyy...
  ...xxxxxxxxxxxxxxxxxxxxxxxxxx...
  ...wwwwwwwwwwwwwwwwwwwwwwwwww...
  .....yxw.................yxw....
  .....yxw.................yxw....
  .....yxw.................yxw....
  .....yxw.................yxw....
  .....yxwwwwwwwwwwwwwwwwwwyxw....
  .....yxw.................yxw....
  .....yxw.................yxw....
  .....yxw.................yxw....
  ................................
  ................................
`);

/** A heavy table against the back wall, seen from the front: a lit top on two legs and a stretcher. */
export const BENCH: SpriteDef = {
  id: 'bench',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: { w: 'wood.1', x: 'wood.2', y: 'wood.3', z: 'wood.4' },
  animations: { still: [BENCH_STILL] },
};

const BENCH_SIDE_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........zzzzzzzzzx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zxyyyyyyyx...........
  ...........zxxxxxxxxx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zxxxxxxxxx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........zyyyyyyyyx...........
  ...........xxxxxxxxxx...........
  ...........wwwwwwwwww...........
  ............xw....xw............
  ............xw....xw............
  ............xw....xw............
  ............xw....xw............
  ............xw....xw............
  ................................
  ................................
`);

/** The same table against a side wall, seen along its length. */
export const BENCH_SIDE: SpriteDef = {
  id: 'bench-side',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: { w: 'wood.1', x: 'wood.2', y: 'wood.3', z: 'wood.4' },
  animations: { still: [BENCH_SIDE_STILL] },
};

const CRATES_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..........zyyyyyyyyyw...........
  ..........yxxxxxxxxxw...........
  ..........yxwxxxxxwxw...........
  ..........yxxwxxxwxxw...........
  ..........yxxxwxwxxxw...........
  ..........yxxxxwxxxxw...........
  ..........yxxxwxwxxxw...........
  ..........yxxwxxxwxxw...........
  ..........yxwxxxxxwxw...........
  ..........yxxxxxxxxxw...........
  ..........wwwwwwwwwwv...........
  ....zyyyyyyyyyw.zyyyyyyyyyw.....
  ....yxxxxxxxxxw.yxxxxxxxxxw.....
  ....yxwxxxxxwxw.yxwxxxxxwxw.....
  ....yxxwxxxwxxw.yxxwxxxwxpq.....
  ....yxxxwxwxxxw.yxxxwxwxpqqp....
  ....yxxxxwxxxxw.yxxxxwxxoqqpo...
  ....yxxxwxwxxxw.yxxxwxwxoppoo...
  ....yxxwxxxwxxw.yxxwxxxwxooo....
  ....yxwxxxxxwxw.yxwxxxxxwxw.....
  ....yxxxxxxxxxw.yxxxxxxxxxw.....
  ....wwwwwwwwwwv.wwwwwwwwwwv.....
  ................................
  ................................
`);

/** Two crates on the floor and one on top, and a sack slumped against them. */
export const CRATES: SpriteDef = {
  id: 'crates',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    o: 'ochre.1',
    p: 'ochre.2',
    q: 'ochre.3',
  },
  animations: { still: [CRATES_STILL] },
};

const BED_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ..........zzzzzzzzzzzz..........
  ..........yyyyyyyyyyyy..........
  ..........yyyyyyyyyyyy..........
  ..........yyyyyyyyyyyy..........
  ..........wwwwwwwwwwww..........
  ..........xxxuuuuuuxxx..........
  ..........xxuuuuuuutxx..........
  ..........xxttttttttxx..........
  ..........xxxxxxxxxxxx..........
  ..........xuuuuuuuuuux..........
  ..........xttttttttttx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIGGGGGGGGGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIGGGGGGGGGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xIHHHHHHHHGx..........
  ..........xFFFFFFFFFFx..........
  ..........vxxxxxxxxxxv..........
  ................................
  ................................
`);

/** A bed against a side wall, seen from above: a headboard, a pillow, a blanket turned down. */
export const BED: SpriteDef = {
  id: 'bed',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    t: 'linen.3',
    u: 'linen.4',
    F: 'crimson.0',
    G: 'crimson.1',
    H: 'crimson.2',
    I: 'crimson.3',
  },
  animations: { still: [BED_STILL] },
};

const COUNTER_STILL = grid(`
  ................................................................
  ................................................................
  ................................................................
  ................................................................
  .............................................MM.................
  ............................................MjjM................
  ............................................MiiM................
  ...............ttttt.........................MM.................
  ..............tuuuuut........................NN.................
  ........zzzzzzFGGGGGFzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz........
  ........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy........
  ........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy........
  ........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy........
  ........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy........
  ........zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz........
  ........xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx........
  .........yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxw.........
  .........yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxw.........
  .........yxxvvvvvvvvxxvvvvvvvvxxvvvvvvvvxxvvvvvvvvxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxvxxxxxxyxxxxw.........
  .........yxxvyyyyyyyxxvyyyyyyyxxvyyyyyyyxxvyyyyyyyxxxxw.........
  .........yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxw.........
  .........yxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxw.........
  .........yvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvw.........
  ................................................................
  ................................................................
`);

/**
 * A counter to be served across: a lit top over a panelled front, a ledger
 * and a lamp on it. Stood between whoever works in a room and the door, it
 * hides their legs to the knee, which is what makes a person in a room a
 * shopkeeper rather than somebody standing in one.
 */
export const COUNTER: SpriteDef = {
  id: 'counter',
  kind: 'prop',
  width: 64,
  height: 32,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    M: 'metal.0',
    N: 'metal.1',
    i: 'fire.3',
    j: 'fire.4',
    t: 'linen.3',
    u: 'linen.4',
    F: 'crimson.0',
    G: 'crimson.1',
  },
  animations: { still: [COUNTER_STILL] },
};
