import { grid, type SpriteDef } from '../format';

/**
 * What a forager works (version 2 phase E2): a clump of something growing,
 * leaves heaped low and flowering stems standing out of it, lit from the
 * top-left. Drawn once, in `nature` for the leaves and `bone` for the flowers,
 * and recoloured into each herb (`HERB_VARIANTS`), the way a vein is drawn in
 * `ore`: one shape, which is what `NodeShapeId` is coarse to buy, told apart by
 * the colours a forager learns them by. What a cut patch leaves is the
 * stubble, since a patch that vanished would take with it the thing a player
 * looks at to see whether it is back.
 */

const HERB_STANDING = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................r...............
  ............r..rqq..r...........
  ...........rqq..pp.rqq..........
  ............pp..c...pp..........
  ........r...b...b...b...r.......
  .......rqq..c.r.c.r.c..rqq......
  ........pp..brqqbrqqb...pp......
  .........c...cppc.pp...c........
  .........b...bb.b.bb...b........
  .........c...rc.c.cr...c........
  ..........r.rqqcccrqq.r.........
  .........rqqdppccccpprqq........
  .......ddeppeeeeeeddcbppbb......
  ......ddceeeeeeddeedceddcbb.....
  ......cceeddeeddcdcceddcddd.....
  .....cceeeddddceddddddddddcc....
  .....cceeddcccddeddddcddcccb....
  .....ccdeddcbddddddddddccbbb....
  ......cedcccdccdddddcccbbba.....
  ......bbccbbccbcddccbbbbaaa.....
  .......bbbabaaaccccbbaaaaa......
  .........aaaaaaacbbaaaaa........
  ............aaaaaaaaa...........
  ................................
  ................................
  ................................
`);

const HERB_CUT = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..........c.....c.c.....c.......
  ........c.b.c.c.b.b.....b.......
  ........b.b.b.b.b.b.c.c.b.......
  .........ccccccccccccbbb........
  .......cccccccccbbbbbbbbbb......
  ......cccccbbbbbbbbbbbbbaaa.....
  .......bbbbbbbbbbbbaaaaaaa......
  .........bbbbbaaaaaaaaaa........
  ................a...............
  ................................
  ................................
`);

/**
 * Each herb in its own colours, by the ramps it swaps: samphire is all green
 * succulent tips, meadowsweet the drawing's own cream heads on green, bog
 * myrtle a drab shrub with brown catkins, and bogbean pale pink flowers over
 * leaves the colour of the fen's water.
 */
export const HERB_VARIANTS = {
  samphire: { nature: 'green', bone: 'green' },
  'bog-myrtle': { nature: 'oilskin', bone: 'ochre' },
  bogbean: { nature: 'furBog', bone: 'skinPale' },
} as const;

export const HERB: SpriteDef = {
  id: 'herb',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'nature.0',
    b: 'nature.1',
    c: 'nature.2',
    d: 'nature.3',
    e: 'nature.4',
    p: 'bone.2',
    q: 'bone.3',
    r: 'bone.4',
  },
  animations: { still: [HERB_STANDING], spent: [HERB_CUT] },
  variants: HERB_VARIANTS,
};
