import { grid, type SpriteDef } from '../format';
import type { ColourRef } from '../palette';

/**
 * Every item's picture in the HUD (B8, decision 111): the gear as it is worn
 * and held in the world, and what a pack is filled with. Drawn at 32 pixels,
 * the size of a tile, and shown one art pixel to a CSS pixel, so an item in the
 * bag is drawn at the size the world draws it on a phone.
 *
 * Gear is drawn in the ramps `art/icons.ts` dyes it out of (a piece in `tier`,
 * a blade in `metal`, a haft in `wood`, fittings in `gold` and a stone in
 * `arcane`), and what is not gear in the ramp of its plainest self, raw and
 * uncooked; cooking, burning, curing and smelting are recolours.
 *
 * Painted by a generator out of shapes shaded by the style guide's light and
 * pasted in as the pictures it made, as the trees were (decision 109).
 */

function icon(id: string, legend: Readonly<Record<string, ColourRef>>, rows: string): SpriteDef {
  return { id, kind: 'icon', width: 32, height: 32, legend, animations: { still: [grid(rows)] } };
}

export const RUSTY_SWORD = icon(
  'icon-rusty-sword',
  {
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    i: 'oreIron.3',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
    q: 'leather.1',
    r: 'leather.2',
    s: 'leather.3',
    t: 'leather.4',
    v: 'gold.1',
    w: 'gold.2',
    x: 'gold.3',
    y: 'gold.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ..........................d.....
    ........................ed......
    ......................ddcb......
    .....................didb.......
    ....................ecdcb.......
    ...................eccbb........
    ..................eccbb.........
    .................dccbbi.........
    ................didbb...........
    ...............ecdbb............
    ..............eccbb.............
    .............eccbb..............
    ............ecbbb...............
    .....n.....ebbici...............
    ....nmn...ebibc.................
    .....nmn.eccbb..................
    ......nmndcbb...................
    .......nlndb....................
    .......tsnn.....................
    ......trqnmn....................
    .....trq..nmn...................
    ...yxsq....nmm..................
    ..yxxw......m...................
    ..xwwv..........................
    ...vv...........................
    ................................
    ................................
`,
);

export const CUTLASS = icon(
  'icon-cutlass',
  {
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    g: 'gold.1',
    h: 'gold.2',
    i: 'gold.3',
    j: 'gold.4',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ................................
    ................................
    .........................d......
    .........................d......
    .......................edcc.....
    ......................eccb......
    ....................edcbb.......
    ...................eccb.........
    ..................eccb..........
    .................eccb...........
    ................eccb............
    ...............eccb.............
    ..............eccb..............
    .............eccb...............
    .............dccb...............
    ............eccb................
    ...........eccb.................
    ..........eccb..................
    .....ji...dccb..................
    .....ihi.eccb...................
    ......ihidccb...................
    .......igidb....................
    .......onii.....................
    ......omlihi....................
    .....oml..ihi...................
    .....nl....ig...................
    ....ji.....h....................
    ...jhhi...i.....................
    ...iggg..i......................
    .......ih.......................
    ................................
`,
);

export const LEAF_BLADE = icon(
  'icon-leaf-blade',
  {
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    g: 'gold.1',
    h: 'gold.2',
    i: 'gold.3',
    j: 'gold.4',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
    s: 'red.3',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    .......................eddd.....
    ......................ecccb.....
    .....................eccccb.....
    ...................edcccccb.....
    ..................eccccdcb......
    .................eccccdcb.......
    ................eccccdcb........
    ...............eccccdccb........
    ..............eccccdccb.........
    .............eccccdccb..........
    ............eccccdccb...........
    ............dcccdccb............
    ...........ecccdccb.............
    .....j....ecccdccb..............
    ....jjj...dccdcbb...............
    .....jjj.eccdcb.................
    ......jjjdcdbb..................
    .......jihdb....................
    .......onsg.....................
    ......omlggg....................
    .....oml..ggg...................
    ...jinl....ggg..................
    ..jiih......g...................
    ..ihhg..........................
    ...gg...........................
    ................................
    ................................
`,
);

export const APPRENTICE_STAFF = icon(
  'icon-apprentice-staff',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'wood.1',
    h: 'wood.2',
    i: 'wood.3',
    j: 'wood.4',
  },
  `
    ................................
    ................................
    ................................
    ........................jii.....
    .......................jjiih....
    ......................jjjiihg...
    ......................iiiihhg...
    ......................iihhhgg...
    ......................hhhggg....
    .....................hggggg.....
    ....................edg.........
    ...................ecb..........
    ..................ecb...........
    .................ecb............
    ................ecb.............
    ...............ecb..............
    ..............ecb...............
    .............ecb................
    ............ecb.................
    ...........ecb..................
    ..........ecb...................
    .........ecb....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    .....ecb........................
    ....ecb.........................
    ...ecb..........................
    ...db...........................
    ................................
    ................................
    ................................
`,
);

export const CRYSTAL_STAFF = icon(
  'icon-crystal-staff',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'arcane.1',
    h: 'arcane.2',
    i: 'arcane.3',
    j: 'arcane.4',
  },
  `
    ................................
    ................................
    ........................i.......
    .......................jhi......
    ......................jjjhi.....
    .....................jhjhhhi....
    ....................ihhhhhhhh...
    ....................dihhhhhg....
    ....................ddihhhg.....
    ...................ecb.ihg......
    ...................db.edhd......
    ...................dcdcbdb......
    ..................ecbbb.........
    .................ecb............
    ................ecb.............
    ...............ecb..............
    ..............ecb...............
    .............ecb................
    ............ecb.................
    ...........ecb..................
    ..........ecb...................
    .........ecb....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    .....ecb........................
    ....ecb.........................
    ...ecb..........................
    ..ecb...........................
    ..db............................
    ................................
    ................................
`,
);

export const BARROW_STAFF = icon(
  'icon-barrow-staff',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'gold.1',
    h: 'gold.2',
    i: 'gold.3',
    j: 'gold.4',
    l: 'arcane.1',
    m: 'arcane.2',
    n: 'arcane.3',
    o: 'arcane.4',
  },
  `
    ................................
    .......................i........
    .......................i........
    .......................i........
    ...................i...hon......
    ...................i..ionnm.....
    ...................i.oinnnml....
    ...................i.ninnmml....
    ...................iinhnmmll.i..
    ....................iimmmlliig..
    ....................ig.liih.....
    ...................jhhii........
    ..................jhggggi.......
    .................jhg....iiiii...
    ................jhg.............
    ...............dig..............
    ..............ecc...............
    .............ecb................
    ............ecb.................
    ...........ecb..................
    ..........ecb...................
    .........ecb....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    .....dcb........................
    ....jic.........................
    ...jhg..........................
    ..jhg...........................
    ..ig............................
    ................................
    ................................
`,
);

export const FELLING_AXE = icon(
  'icon-felling-axe',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
  },
  `
    ................................
    ................................
    ................................
    ..........j.....................
    ........jjhii...................
    ........jhhhhi....n.............
    .......jjhhhhhii..nn............
    .......jjhhhhhhhinmmnd..........
    .......jghhhhhhhhinmmn..........
    .......j.ihhhhhhhhinmmm.........
    .......j.ihhhhhhhhhinl..........
    ..........igggghhhhg............
    ...............iggg.............
    ...............edc..............
    ...............db...............
    ..............ecb...............
    .............ecb................
    ............ecb.................
    ...........ecb..................
    ..........ecb...................
    .........ecb....................
    .........db.....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    ......db........................
    .....ecb........................
    ....ecb.........................
    ....db..........................
    ................................
    ................................
    ................................
`,
);

export const BEARDED_AXE = icon(
  'icon-bearded-axe',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
  },
  `
    ................................
    ................................
    ................................
    ..................n.............
    ...............ji.nn............
    ..............jhgnmmn...........
    ............jihhhinmmnd.........
    ...........jhhhhhhinmmn.........
    ...........jhhhhhhhinmmm........
    ..........jhhhhhhhhgdnl.........
    ..........jhhhhhhhgeb...........
    ..........jhhhhhhgeb............
    .........jhhhhhhgeb.............
    .........jhhhhhgeb..............
    .........jhhhhhgdb..............
    .........jhhhhgeb...............
    ..........jhggeb................
    ..........jgedb.................
    ..........jecbb.................
    ..........ecb...................
    .........ecb....................
    .........db.....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    ......db........................
    .....ecb........................
    ....ecb.........................
    ....db..........................
    ................................
    ................................
    ................................
`,
);

export const PICKAXE = icon(
  'icon-pickaxe',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
    o: 'metal.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ..................jiii..........
    ...............jiihgghiiii......
    .............jihgggonihhhhi.....
    ............jhhgonnmligghhhi....
    ...........jhhggnmmml...ighhh...
    ..........jhhg...nmmmn....ig....
    .........jhhg....nmmml..........
    ........ihhg.....nllll..........
    .........ig.....edc.............
    ................db..............
    ...............ecb..............
    ..............ecb...............
    .............ecb................
    .............db.................
    ............ecb.................
    ..........edcb..................
    .........ecbb...................
    .........db.....................
    ........ecb.....................
    .......ecb......................
    ......ecb.......................
    ......db........................
    .....ecb........................
    ....ecb.........................
    ....db..........................
    ................................
    ................................
    ................................
`,
);

export const MAUL = icon(
  'icon-maul',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ................................
    ................................
    ..................i.............
    .................jhiii..........
    ................jhhhhhiii.......
    ...............jhhhghhhhhi......
    ..............jhhhhhhhhhhhi.....
    .............ihhhhhhhhhhhhg.....
    ..............ihhhhhhhhhghg.....
    ..............ihhhgghhhhhhhi....
    ...............ihgonihhhhhhg....
    ...............igomlihhhhhhg....
    ...............homljhghhhhg.....
    ...............omljhhhhhhg......
    ..............omldigghhhg.......
    ..............nleb...igg........
    .............eddcb..............
    ............ecccb...............
    ...........ecccb................
    ..........ecccb.................
    .........ecccb..................
    ........ecccb...................
    .......ecccb....................
    ......ecccb.....................
    ......dccb......................
    .....eccb.......................
    ....ecccb.......................
    ....dccb........................
    ....dbb.........................
    ................................
    ................................
`,
);

export const FISHING_POLE = icon(
  'icon-fishing-pole',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'leather.1',
    h: 'leather.2',
    i: 'leather.3',
    j: 'leather.4',
    m: 'linen.2',
    n: 'linen.3',
    q: 'red.1',
    s: 'red.3',
    t: 'red.4',
    w: 'bone.2',
    x: 'bone.3',
  },
  `
    ................................
    ................................
    ................................
    ........................ed......
    .......................ecbn.....
    ......................ecb.n.....
    .....................ecb..n.....
    .....................db...n.....
    ....................ecb...n.....
    ...................ecb....n.....
    ..................ecb.....n.....
    .................ecb......n.....
    ................ecb.......nn....
    ................db.........n....
    ...............ecb.........n....
    .............edcb..........n....
    ............ecbb...........n....
    ...........ecb.............n....
    ..........ecb..............n....
    ..........db...............n....
    .........ecb...............m....
    ........ecb................ts...
    .......ecb.................sq...
    ......ecb..................xw...
    .....dbb........................
    .....ji.........................
    ....jhg.........................
    ...jhg..........................
    ..jhg...........................
    .jhg............................
    .ig.............................
    ................................
`,
);

export const SHORT_BOW = icon(
  'icon-short-bow',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'linen.1',
    i: 'linen.3',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ................................
    ................................
    ..........................ed....
    ..........................db....
    ..........................id....
    .........................ieb....
    ........................i.db....
    .......................i..db....
    ......................i...db....
    .....................i....db....
    ....................i....ecb....
    ...................i.....db.....
    ..................i......db.....
    .................i......ecb.....
    ................i.......dcb.....
    ...............ig.......db......
    ..............i........ecb......
    .............i........ecb.......
    ............i......on.dcb.......
    ...........i.......nmndb........
    ..........i.........nmn.........
    .........i........eddnmn........
    ........i........eccb.nl........
    .......i......eddcbb............
    ......i....eddccbb..............
    ...edieddddcbbbb................
    ...dbdbbbbbb....................
    ................................
    ................................
    ................................
    ................................
`,
);

export const LONGBOW = icon(
  'icon-longbow',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'linen.1',
    i: 'linen.3',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ................................
    ...........................ed...
    ...........................db...
    ...........................id...
    ..........................ieb...
    .........................ieb....
    ........................i.db....
    .......................i..db....
    ......................i..ecb....
    .....................i...db.....
    ....................i...ecb.....
    ...................i....dcb.....
    ..................i....ecb......
    .................i.....dcb......
    ................i.....ecb.......
    ...............ig....ecb........
    ..............i......dcb........
    .............i....ondcb.........
    ............i.....nmnc..........
    ...........i......dnmn..........
    ..........i.....edccnmn.........
    .........i.....eccb..nl.........
    ........i....edcbb..............
    .......i...edccb................
    ......i..edccbb.................
    .....ieddcbbb...................
    ..ediebbbb......................
    ..dbdb..........................
    ................................
    ................................
    ................................
`,
);

export const ROUND_SHIELD = icon(
  'icon-round-shield',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'metal.1',
    i: 'metal.3',
    j: 'metal.4',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
    o: 'metal.4',
  },
  `
    ................................
    ................................
    ................................
    ...........jiiiiiiiii...........
    .........jiggeeebddigii.........
    ........jggbeeeebddddigi........
    ......jigeebeeeebddddbdiii......
    ......igeeebeeeebddddbdcig......
    .....jgeeeebeeedbddddbcccii.....
    ....jgeeeeebeeedbddddbccccii....
    ....igeeeeebeeddbddddbccccig....
    ...jgeeeeeebedddbddddbcccccii...
    ...igeeeeeebdddnnddddbccccbig...
    ...ieeeeeedbdooonnmdcbccccbbi...
    ...ideeddddbdoonnnmccbccccbbi...
    ...idddddddbnonnnmmlcbcccbbbi...
    ...idddddddbnnnnmmllcbccbbbbi...
    ...idddddddbdmmmmllccbccbbbbi...
    ...idddddddbdlmllllccbcbbbbbi...
    ...iiddddddbdccllccccbbbbbbjg...
    ...igdddddcbccccbccccbbbbbbig...
    ....iicccccbccccbccbbbbbbbjg....
    ....igcccccbccccbcbbbbbbbbig....
    .....iiccccbccccbbbbbbbbbjg.....
    ......iicccbcccbbbbbbbbbjg......
    ......igiccbbbbbbbbbbbbjgg......
    ........iiibbbbbbbbbbjig........
    .........igiibbbbbbjigg.........
    ...........igiiiiiigg...........
    ................................
    ................................
    ................................
`,
);

export const HEATER_SHIELD = icon(
  'icon-heater-shield',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'metal.1',
    h: 'metal.2',
    i: 'metal.3',
    j: 'metal.4',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
    o: 'gold.4',
  },
  `
    ................................
    ................................
    ................................
    .....jiiiiiiiiiiiiiiiiiiiii.....
    .....ihgggggggggggggggggghg.....
    .....igedddddddonedddddddig.....
    .....igdccccccbnldccccccbig.....
    .....igdccccccbnldccccccbig.....
    .....igdccccccbnldccccccbig.....
    .....igdccccccbnldccccccbig.....
    .....igdbbbbbbbnldbbbbbbbig.....
    .....igonnnnnnnmmnnnnnnnnni.....
    .....ignlllllllmmllllllllli.....
    .....igedddddddnledddddddjg.....
    .....igdccccccbnldccccccbig.....
    .....igdccccccbnldccccccbig.....
    ......iidcccccbnldcccccbjg......
    ......igdcccccbnldcccccbig......
    .......idcccccbnldcccccbig......
    .......iidccccbnldccccbjg.......
    .......igdccccbnldccccbig.......
    ........iidcccbnldcccbjg........
    .........iidccbnldccbjg.........
    ..........iidcbnldcbjg..........
    ...........iidbnldbjg...........
    ............iicnlcjg............
    .............iinljg.............
    ..............iiig..............
    ...............ig...............
    ................................
    ................................
    ................................
`,
);

export const ORB = icon(
  'icon-orb',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'arcane.1',
    h: 'arcane.2',
    i: 'arcane.3',
    j: 'arcane.4',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
  },
  `
    ................................
    ................................
    ................................
    ................................
    .............eedddd.............
    ...........eeeeeddddc...........
    .........eeeeeeedddddcc.........
    ........eeeeeeeedddddccc........
    ........eeeeeeeddddddccc........
    .......eeeeeeeedddddccccb.......
    .......eeeeeeeddddddccccb.......
    ......deeeeeedjjiihcccccbb......
    ......deeeeddjjjjiihcccbbb......
    ......ddddddjjjjiihhgccbbb......
    ......ddddddjjjiiihhgcbbbb......
    ......ddddddiiiiihhggbbbbb......
    ......ddddddiiiihhhggbbbbb......
    .......cdddchhhhhggggbbbb.......
    .......cccccchhhggggbbbbb.......
    ........ccccccgggggbbbbb........
    ........ccccccbbbbbbbbbb........
    .........nnnnnnnnnnnnnm.........
    ..........nmmmmmmmmmml..........
    ..........nmmmmmmmmmml..........
    ...........nlllllllll...........
    ................................
    ..........nnnnnnnnnnnm..........
    ...........nmmmmmmmml...........
    ............nlllllll............
    ................................
    ................................
    ................................
`,
);

export const LANTERN = icon(
  'icon-lantern',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'arcane.1',
    h: 'arcane.2',
    i: 'arcane.3',
    j: 'arcane.4',
  },
  `
    ................................
    ...............dc...............
    .............ec..dd.............
    .............c....c.............
    ............d......d............
    ............c......c............
    ................................
    ..........eddddddddddd..........
    .........eccccccccccccd.........
    ........dcbbbbbbcbbbbbbd........
    .........djjjjjjdiihhhhd........
    .........djjjjjjdiihhhgd........
    .........djjjjjjdiihhggd........
    .........djjjjjidiihhhgd........
    .........djjjjjidiihhhgd........
    .........djjjiiidihhhggd........
    .........diiiiiidhhhhggd........
    .........diiiiiidhhhgggd........
    .........diiiiihdhhggggd........
    .........diiihhhdhgggggd........
    .........dhhhhhhdggggggd........
    .........dghhhhgdggggggd........
    .........dggggggdggggggd........
    .........dggggggdggggggd........
    ........ecddddddcddddddb........
    ........dccccccccccccccb........
    .......eccccccccccccccccd.......
    .......dbbbbbbbbbbbbbbbbb.......
    ................................
    ................................
    ................................
    ................................
`,
);

export const QUIVER = icon(
  'icon-quiver',
  {
    c: 'wood.2',
    d: 'wood.3',
    g: 'bone.1',
    h: 'bone.2',
    i: 'bone.3',
    j: 'bone.4',
    l: 'tier.1',
    m: 'tier.2',
    n: 'tier.3',
    o: 'tier.4',
    q: 'leather.1',
    r: 'leather.2',
    s: 'leather.3',
    t: 'leather.4',
    v: 'leather.1',
    w: 'leather.2',
    x: 'leather.3',
    y: 'leather.4',
  },
  `
    ................................
    ................................
    ..................jh............
    ..............jh.ig.............
    .............ig..d....jh........
    .............d...c...ig.........
    .............c..d....d..........
    ............d..d.....c..........
    ...........d...c....tss.........
    ...........c..dtssssrrrs........
    ..........tssssrrrrrrqqq........
    .......tssrrrrrrqqqqqon.........
    .......srrqqqqqqonnyxnl.........
    .......sqqonnnnnmmlxvnl.........
    .......onnmmmmmmmmlxwx..........
    .......nmmmmmmmmmmmnxv..........
    ........nmmmmmmmmmmlxv..........
    ........nmmmmmmmmmmlxwx.........
    ........nmmmmmmmmmmmnxv.........
    ........nmmmlmmmmmmmlxwx........
    .........nmmmmmmmmmmlxwv........
    .........nmmmmmlmmml..xwx.......
    .........nmmmmmmmmml...xv.......
    ..........nmmmmmmmml...xv.......
    ..........nmmlmmmml....xwx......
    ..........nmmmmmmml.....xv......
    ..........nmmmmmmml.....xv......
    ...........nmmmmml..............
    ...........nllllll..............
    ................................
    ................................
    ................................
`,
);

export const CAP = icon(
  'icon-cap',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'tier.1',
    h: 'tier.2',
    i: 'tier.3',
    j: 'tier.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .............eedddd.............
    ..........eeeeeedddddc..........
    .........eeeeeeebdddddc.........
    ........eeeeeeeebdddddcc........
    .......eeebeeeeebdddddbcc.......
    ......eeeeeeeeedbdddddcccc......
    .....eeeebeeeeedbddddccbccb.....
    .....eeeeeeeeeddbddddcccccb.....
    .....eeebeeeedddbdddccccbbb.....
    ....deeeeeedddddbdddcccccbbb....
    ....ddeeedddddddbddccccccbbb....
    ....ddddddddddddbdccccccbbbb....
    ....jiiiiiiiiiiiiiiiiiiiiiii....
    ....ihjhhhjhhhjhhhjhhhjhhhjg....
    ....ihhhhhhhhhhhhhhhhhhhhhhg....
    ....iggggggggggggggggggggggg....
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const HELM = icon(
  'icon-helm',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'tier.1',
    h: 'tier.2',
    i: 'tier.3',
    j: 'tier.4',
    k: 'ink.0',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ...........eeeeeddddc...........
    ..........eeeeeedddddc..........
    .........eeeeeeeddddddc.........
    ........eeeeeeeeddddddcc........
    .......eeeeeeeeeddddddccc.......
    ......eeeeeeeeeddddddccccb......
    ......eeeeeeeedddddddccccb......
    .....eeeeeeeeedddddddccccbb.....
    .....eeeeeeeedddddddcccccbb.....
    .....deeeeeddddddddccccccbb.....
    .....ddeeddddddddddcccccbbb.....
    .....jiiiiiiiiiiiiiiiiiiiii.....
    .....ihjhhhjhhhhhhhhhjhhhjg.....
    .....ihhhhhhhhhhhhhhhhhhhhg.....
    .....iggggggggghhhggggggggg.....
    .....dddkkkkkkcihgckkkkkkbb.....
    .....ccdkkkkkkcihgckkkkkkbb.....
    ......cckkkkkkcihgbkkkkkkb......
    ......cckkkkkkcihgbkkkkkkb......
    ...............ihg..............
    ...............ihg..............
    ...............ihg..............
    ...............igg..............
    ................................
    ................................
    ................................
    ................................
`,
);

export const HAT = icon(
  'icon-hat',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'tier.1',
    h: 'tier.2',
    i: 'tier.3',
    j: 'tier.4',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
    o: 'gold.4',
  },
  `
    ................................
    ................................
    .................d..............
    ................ecdd............
    ...............eccccd...........
    ..............eccccbb...........
    ..............dcccb.............
    ..............dcccb.............
    .............ecccccd............
    .............dcccccb............
    .............dcccccb............
    ............eccccccb............
    ............dcccccccd...........
    ............dcccccccb...........
    ...........eccccccccb...........
    ...........dccccccccb...........
    ...........dcccccccccd..........
    ..........eccccccccccb..........
    ..........dbbbbbbbbbbb..........
    .........onnnnnnnnnnnnnn........
    .......jinmmmmmmmmmmmmmli.......
    ....jiihgnlllllllllllllliiii....
    ..jihhhhhiiiiiiiiiiiiiiihhhhii..
    ..ihhhhhhhhhhhhhhhhhhhhhhhhhhg..
    ..ighhhhhhhhhhhhhhhhhhhhhhhhgg..
    ....igghhhhhhhhhhhhhhhhhhggg....
    .......iggggggggggggggggg.......
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const HOOD = icon(
  'icon-hood',
  { b: 'tier.1', c: 'tier.2', d: 'tier.3', e: 'tier.4', f: 'ink.0', n: 'ink.3' },
  `
    ................................
    ................................
    ...............ed...............
    ..............ecbd..............
    ............edccbcdd............
    ..........edcccbccccdd..........
    .........eccccccccccccd.........
    ........eccccccccccccccd........
    .......eccccccccccccccccd.......
    .......dcccccbbbbbbcccccb.......
    ......eccccbbffffffdbccccd......
    ......dcccbffffffffffdcccb......
    ......dcccbffffffffffdcccb......
    .....ecccbffffffffffffdcccd.....
    .....dcccbffffffffffffdcccb.....
    ....ecccbffffffffffffffdcccd....
    ....dcccbffffffffffffffdcccb....
    ....dcccbffffffffffffffdcccb....
    ....dcccbffffnfffffnfffdcccb....
    ....dcccbffffffffffffffdcccb....
    ....dcccbffffffffffffffdcccb....
    ....dccccdffffffffffffeccccb....
    .....dcccbffffffffffffdcccb.....
    .....dccccdffffffffffeccccb.....
    .....dccccbffffffffffdccccb.....
    .....dcccccddffffffedcccccb.....
    .....dcccccccddddddcccccccb.....
    .....dbbbbbbbbbbbbbbbbbbbbb.....
    ................................
    ................................
    ................................
    ................................
`,
);

export const COWL = icon(
  'icon-cowl',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'tier.1',
    h: 'tier.2',
    i: 'tier.3',
    j: 'tier.4',
    k: 'ink.0',
    s: 'ink.3',
  },
  `
    ................................
    ................................
    ...............ed...............
    .............edccdd.............
    ............eccccccd............
    ..........edccccccccdd..........
    .........eccccccccccccd.........
    ........eccccccccccccccd........
    ........dccccbbbbbbccccb........
    ........dcccbkkkkkkdcccb........
    .......ecccbkkkkkkkkdcccd.......
    .......dccbkkkkkkkkkkdccb.......
    .......dccbkkkkkkkkkkdccb.......
    ......ecccbkkkkkkkkkkdcccd......
    ......dcccbkkkkkkkkkkdcccb......
    ......dcccbkkkskkkskkdcccb......
    .......dccbkkkkkkkkkkdccb.......
    .......dccbkkkkkkkkkkdccb.......
    .....jidccbkkkkkkkkkkdccbji.....
    ...jihgdcccdkkkkkkkkecccbihii...
    ..jhhhhidcccdkkkkkkecccbjhhhhi..
    ..ihhhhgdbbbbddddddbbbbbihhhhg..
    ..ihhhhhiiiiiiiiiiiiiiiihhhhhg..
    ..ihhhhhhhhhhhhhhhhhhhhhhhhhhg..
    ..ihhhhhhhhhhhhhhhhhhhhhhhhhhg..
    ..ihhhhhhghhhhhhghhhhhgghhhhhg..
    ...ihhhhg.ihhhhg.ihhhg..ihhhg...
    ....ihhg...ihhg...ihg....ihg....
    .....ig.....ig.....h......h.....
    ................................
    ................................
    ................................
`,
);

export const BANDANA = icon(
  'icon-bandana',
  { b: 'tier.1', c: 'tier.2', d: 'tier.3', e: 'tier.4', j: 'bone.4' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    .............................d..
    ............................eb..
    ..........................edcb..
    ....ddddddddddddddddddddddccbb..
    ....dddddddddddddddddddddddd....
    ....ddddddddddddddddddddcddd....
    .....dccccccbcccccccccccccb.....
    .....dcccccbjdccccccccbcccb.....
    ......dcccbcdcccccbccbjdcbcd....
    .......dcbjdcccccbjdccdcb.db....
    ........dcdcccccccdccccb........
    ........dcccccbcccccbccb........
    .........dcccbjdcccbjdb.........
    ..........dcccdcccccdb..........
    ...........dcccccccccb..........
    ...........dccccbcccb...........
    ............dccbjdcb............
    .............dccdcb.............
    .............dccccb.............
    ..............dccb..............
    ...............db...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const CROWN = icon(
  'icon-crown',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'red.1',
    h: 'red.2',
    i: 'red.3',
    j: 'red.4',
    n: 'arcane.3',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ....ed....d....ed....d....ed....
    ...eecd..ecd..eecd..ecd..eecd...
    ...dccb..dcb..dccb..dcb..dccb...
    ....db....d....db....d....db....
    ....db....d....db....d....db....
    ....db....dd...db....dd...db....
    ....db...ecb...db...ecb...db....
    ...eccd..dcb..eccd..dcb..eccd...
    ...dccb.ecccd.dccb.ecccd.dccb...
    ..eccccdcccccdccccdcccccdccccd..
    ..dbccccccccccccccccccccccccbb..
    ....dccccccccccccccccccccccb....
    ....eeeeeeeeeeeeeeeeeeeeeeee....
    ....eeeeeeeeeejjiheeeeeeeeee....
    ....dccccbcccbjjihdccccbcccb....
    ....dcccbndcbiiihhgdccbndccb....
    ....dccccdcccdhhhgeccccdcccb....
    ....dccccccccbggggdccccccccb....
    ....dcccccccccddddcccccccccb....
    ....dbbbbbbbbbbbbbbbbbbbbbbb....
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const JERKIN = icon(
  'icon-jerkin',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    n: 'linen.3',
    q: 'leather.1',
    r: 'leather.2',
    s: 'leather.3',
    t: 'leather.4',
    v: 'gold.1',
    w: 'gold.2',
    x: 'gold.3',
    y: 'gold.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........edffffffffed..........
    ........edccdffffffeccdd........
    ......edcccccddddddcccccdd......
    .....eccccccccccbcccccccccd.....
    .....dcccccccccbbcccccccccb.....
    ......dcccccccbnbbccccccccb.....
    ......dccccccccdbndccccccb......
    ......dccccccccbbdcccccccb......
    ......dcccccccbnbbcccccccb......
    ......dccccccccdbndccccccb......
    ......dccccccccbbdcccccccb......
    ......dcccccccbnbbcccccccb......
    ......dccccccccdbndccccccb......
    ......dccccccccbbdcccccccb......
    ......dcccccccbnbbcccccccb......
    ......dccccccccdbndccccccb......
    .......dccccccccbdcccccccb......
    .......dbbbbbbbbbbbbbbbbb.......
    .......tsssssssyxxtsssssss......
    .......srrrrrrqxwvsrrrrrrq......
    .......sqqqqqqqxvvsqqqqqqq......
    .......eddddddddbdddddddd.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dbbbbbbbbbbbbbbbbb.......
    ................................
    ................................
    ................................
`,
);

export const STUDDED_JERKIN = icon(
  'icon-studded-jerkin',
  {
    B: 'metal.1',
    E: 'metal.4',
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    n: 'linen.3',
    q: 'leather.1',
    r: 'leather.2',
    s: 'leather.3',
    t: 'leather.4',
    v: 'gold.1',
    w: 'gold.2',
    x: 'gold.3',
    y: 'gold.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........edffffffffed..........
    ........edccdffffffeccdd........
    ......edcccccddddddcccccdd......
    .....eccccccccccbcccccccccd.....
    .....dccccbccccbbccccbccccb.....
    ......dccbEdccbnbbccbEdcccb.....
    ......dcccdBdbcdbndbcdBdcb......
    ......dccccdbEdbbdbEdcdccb......
    ......dccccccdbnbbcdcccccb......
    ......dcccbccccdbndccbcccb......
    ......dccbEdcccbbdccbEdccb......
    ......dcccdBdbbnbbcbcdBdcb......
    ......dccccdbEddbndEdcdccb......
    ......dccccccdcbbdcdcccccb......
    ......dcccbcccbnbbcccbcccb......
    ......dccbEdcccdbndcbEdccb......
    .......dccdBdbccbdcbcdBdcb......
    .......dbbbdbEdbbbbEdbdbb.......
    .......tsssssssyxxtsssssss......
    .......srrrrrrqxwvsrrrrrrq......
    .......sqqqqqqqxvvsqqqqqqq......
    .......eddddddddbdddddddd.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dbbbbbbbbbbbbbbbbb.......
    ................................
    ................................
    ................................
`,
);

export const PLATE = icon(
  'icon-plate',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    l: 'tier.1',
    m: 'tier.2',
    n: 'tier.3',
    o: 'tier.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........edffffffffed..........
    ....ooooodccdffffffecccmmmml....
    ...ooooooodccddddddccbmmmmmll...
    ..noooooooodccccccccbmmmmmmlll..
    ..nnnnnnnnndccccebccbmmmmmllll..
    ..nnnnnnnnndccccebccbmmmllllll..
    ..mnnnnnnnndccccebccbmllllllll..
    ...mmmmmmmeeccccebcccelllllll...
    ....mmmmmeccccccebccccdlllll....
    .......edcccccccebcccccdd.......
    .......dccccccccebccccccb.......
    .......dccccccccebccccccb.......
    .......dccccccccebccccccb.......
    .......dccccccccebccccccb.......
    .......dccccccccebccccccb.......
    .......dccccccccebccccccb.......
    ........dcccccccebccccccb.......
    ........dcccccccebcccccb........
    ........bbbbbbbbbbbbbbbbb.......
    ........bbbbbbbbbbbbbbbbb.......
    ........dccccccccccccccb........
    ........bbbbbbbbbbbbbbbbb.......
    ........bbbbbbbbbbbbbbbbb.......
    ........dccccccccccccccb........
    ........dbbbbbbbbbbbbbbb........
    ................................
    ................................
    ................................
`,
);

export const CLOAKED_PLATE = icon(
  'icon-cloaked-plate',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    l: 'tier.1',
    m: 'tier.2',
    n: 'tier.3',
    o: 'tier.4',
    q: 'crimson.1',
    r: 'crimson.2',
    s: 'crimson.3',
    t: 'crimson.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........edffffffffed..........
    ....ooooodccdffffffecccmmmml....
    ...ooooooodccddddddccbmmmmmll...
    ..noooooooodccccccccbmmmmmmlll..
    ..nnnnnnnnndccccebccbmmmmmllll..
    ..nnnnnnnnndccccebccbmmmllllll..
    ..mnnnnnnnndccccebccbmllllllll..
    ...mmmmmmmeeccccebcccelllllll...
    ....mmmmmeccccccebccccdlllll....
    ....tssedcccccccebcccccddtsss...
    ...trrqdccccccccebccccccbsrrq...
    ...srrqdccccccccebccccccbsrrq...
    ...srrqdccccccccebccccccbsrrq...
    ...srrqdccccccccebccccccbsrrq...
    ...srrqdccccccccebccccccbsrrq...
    ...srrqdccccccccebccccccbsrrq...
    ...srrrsdcccccccebccccccbsrrq...
    ...srrrqdcccccccebcccccbsrrrq...
    ...srrrqbbbbbbbbbbbbbbbbbsrrq...
    ...srrrqbbbbbbbbbbbbbbbbbsrrq...
    ...srrrqdccccccccccccccbsrrrrs..
    ..trrrrqbbbbbbbbbbbbbbbbbsrrrq..
    ..srrrrqbbbbbbbbbbbbbbbbbsrrrq..
    ..srrrrqdccccccccccccccbtrrrrq..
    ..srrrrqdbbbbbbbbbbbbbbbsrrrrq..
    ..sqqqqqssssssssssssssssqqqqqq..
    ................................
    ................................
`,
);

export const ROBE = icon(
  'icon-robe',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
    o: 'gold.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........edffffffffed..........
    .........eccdffffffeccd.........
    ........eccccdddbddccccd........
    ......edccccccccbcccccccdd......
    .....eccccccccccbcccccccccd.....
    ....ecccccccccccbccccccccccd....
    ...eccccccccccccbcccccccccccd...
    ...dccccccccccccbcccccccccccb...
    ...dccccccccccccbcccccccccccb...
    ...dccccbcccccccbccccccbccccb...
    ..eccccb.dbbbbbbbbbbbbb.dccccd..
    ..dccccb.donnnnnnnnnnnn.dccccb..
    ..dcccb.ebnlllllmlllllld.dcccb..
    ..dbccb.dcddddddnedddddb.dccbb..
    ....db..dccccccbmdcccccb..db....
    ........dcccccbndndccccb........
    ........dccccccdbdcccccb........
    ........dcccccccbcccccccd.......
    .......eccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    ......ecccccccccbccccccccd......
    ......dcccccccccbccccccccb......
    ......dbbbbbbbbbbbbbbbbbbb......
    ................................
    ................................
`,
);

export const TRIMMED_ROBE = icon(
  'icon-trimmed-robe',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
    o: 'gold.4',
    q: 'gold.1',
    r: 'gold.2',
    s: 'gold.3',
    t: 'gold.4',
  },
  `
    ................................
    ................................
    .............ffffff.............
    ............ffffffff............
    ..........ecffffffffec..........
    .........ebsdffffffebsd.........
    ........eccdseddbddbsecd........
    ......edcccbsdccbccbsdccdd......
    .....ecccccbrdccbccbrdccccd.....
    ....ecccccccdsdcbcbseccccccd....
    ...ecccccccccdsdbbseccccccccd...
    ...dcccccccccbrdbbrdccccccccb...
    ...dccccccccccdsbsecccccccccb...
    ...dccccbccccccdsecccccbccccb...
    ..eccccb.dbbbbbbrdbbbbb.dccccd..
    ..dccccb.donnnnnnnnnnnn.dccccb..
    ..dcccb.ebnlllllmlllllld.dcccb..
    ..dbbcb.dcddddddnedddddb.dccbb..
    ..sssc..dccccccbmdcccccb..dbtsr.
    ....ssr.dcccccbndndccccb..ssq...
    ........dccccccdbdcccccb........
    ........dcccccccbcccccccd.......
    .......eccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccbcccccccb.......
    ......ecccccccccbccccccccd......
    ......dbbbbbbbbbbbbbbbbbbb......
    ......sssssssssssssssssssr......
    ................................
    ................................
`,
);

export const VEST = icon(
  'icon-vest',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    f: 'ink.0',
    k: 'ink.0',
    q: 'fur.1',
    r: 'fur.2',
    s: 'fur.3',
    t: 'fur.4',
  },
  `
    ................................
    ................................
    ............tsfffftss...........
    .........tssrqffffsrrss.........
    .........srrrqffffsrrrq.........
    ........dsrrqffffffsrrrs........
    ......edtrrrqedkkkdsrrrqed......
    .....ecbsqqqqdbkkkdsqqqqdcd.....
    .....dccdddddcbkkkddddddccb.....
    ......dcccccccbkkkdcccccccb.....
    ......dcccccccbkkkdccccccb......
    ......dcccccccbkkkdccccccb......
    ......dcccccccbkkkdccccccb......
    ......dcccccccbkkkdccbcccb......
    ......dcccbcccbkkkdccccccb......
    ......dcccccccbkkkdccccccb......
    ......dcccccccbkkkdccccccb......
    ......dcccccccbkkkdccccccb......
    ......dcccccbcbkkkdccccccb......
    ......dcccccccbkkkdcbccccb......
    .......dccccccbkkkdccccccb......
    .......dccccccbkkkdcccccb.......
    .......dccccccbkkkdcccccb.......
    .......dcccbccbkkkdcccccb.......
    .......dccccccbkkkdcccbcb.......
    .......dccccccbkkkdcccccb.......
    .......dccccccbkkkdcccccb.......
    .......dccccccbkkkdcccccb.......
    .......dcbcbcbbkkkdbcbcbb.......
    ........b.b.b.b.b.b.b.b.b.b.....
    ................................
    ................................
`,
);

export const BREECHES = icon(
  'icon-breeches',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'leather.1',
    h: 'leather.2',
    i: 'leather.3',
    j: 'leather.4',
    l: 'gold.1',
    m: 'gold.2',
    n: 'gold.3',
    o: 'gold.4',
  },
  `
    ................................
    ................................
    ................................
    .......jiiiiiiionnjiiiiiii......
    .......ihhhhhhgnmlihhhhhhg......
    .......igggggggnlliggggggg......
    .......eddddddddddddddddd.......
    .......dccccccccccccccccb.......
    .......dccccccccccccccccb.......
    .......dcccccccccccccccccd......
    ......eccccccccccccccccccb......
    ......dccccccccccccccccccb......
    ......dccccccccccccccccccb......
    ......dccccccccbbccccccccb......
    ......dcccbcccb..dccccbccb......
    ......dcccccccb..dcccccccb......
    ......dcccccccb..dcccccccb......
    ......dcccccccb..dcccccccb......
    ......dcccccccb..dcccccccb......
    ......dcccccccb..dcccccccb......
    ......dccbcccb....dccccbcb......
    ......dccccccb....dccccccb......
    ......dccccccb....dcccccccd.....
    .....ecccccccb....dcccccccb.....
    .....dcccccccb....dcccccccb.....
    .....dcccccccb....dcccccccb.....
    .....dccccccb......dccccccb.....
    .....bbbbbbbbb.....bbbbbbbbb....
    .....bbbbbbbbb.....bbbbbbbbb....
    ................................
    ................................
    ................................
`,
);

export const GREAVES = icon(
  'icon-greaves',
  {
    b: 'tier.1',
    c: 'tier.2',
    d: 'tier.3',
    e: 'tier.4',
    g: 'tier.1',
    h: 'tier.2',
    i: 'tier.3',
    l: 'leather.1',
    m: 'leather.2',
    n: 'leather.3',
    o: 'leather.4',
  },
  `
    ................................
    ................................
    ................................
    .......onnnnnnnnnnnnnnnnnn......
    .......nmmmmmmmmmmmmmmmmml......
    .......nllllllllllllllllll......
    .......eddddddddddddddddd.......
    .......dccccccccccccccccb.......
    .......dccccccccccccccccb.......
    .......dcccccccccccccccccd......
    ......bbbbbbbbbcccbbbbbbbbb.....
    ......dccccccccccccccccccb......
    ......dcbbbccccccccccbbbcb......
    ......dbiiidcccbbcccbhhhdb......
    ......ciiiiidcb..dcbhhhggc......
    ......iiiiiiidb..dbhhggggg......
    ......hhhhhhhdb..dbggggggg......
    ......dhhhhhecb..dcdgggggd......
    ......ddgggeccb..dccdgggeb......
    ......dcdddcccb..dcccdddcb......
    ......dccccccb....dccccccb......
    ......dccccccb....dccccccb......
    ......dccccccb....dcccccccd.....
    .....ecccccccb....dcccccccb.....
    .....eeeeeeeee....deeeeeeeee....
    .....dcccccccb....dcccccccb.....
    .....dccccccb......dccccccb.....
    .....dccccccb......dccccccb.....
    .....dbbbbbbb......dbbbbbbb.....
    ................................
    ................................
    ................................
`,
);

export const BONES = icon(
  'icon-bones',
  { b: 'bone.1', c: 'bone.2', d: 'bone.3', e: 'bone.4' },
  `
    ................................
    ................................
    ................................
    .....................edd........
    .......edd..........ecccd.......
    ......ecccd.........dccccd......
    .....eccccb.........dcccccd.....
    ....ecccccb..........dccccb.....
    ....dcccccb..........dccccb.....
    ....dccccccd........ecccbb......
    .....dbbbcccd.....edcccb........
    .........dcccd...eccccb.........
    ..........dccb..ecccbb..........
    ...........dccddcccb............
    ...........dccccccb.............
    ............dccccb..............
    .............dccccd.............
    ............eccccccd............
    ..........edcccbbcccd...........
    .........eccccb..dccb...........
    ........ecccbb....dccdddd.......
    ....edddcccb......dccccccd......
    ...eccccccb........dccccccd.....
    ...dcccccb..........dccccccd....
    ...dcccccb...........dcccccb....
    ....dccccb............dbcccb....
    .....dcccb..............dbb.....
    ......dbb.......................
    ................................
    ................................
    ................................
    ................................
`,
);

export const MEAT = icon(
  'icon-meat',
  {
    b: 'red.1',
    c: 'red.2',
    d: 'red.3',
    e: 'red.4',
    g: 'bone.1',
    h: 'bone.2',
    i: 'bone.3',
    j: 'bone.4',
    n: 'bone.3',
  },
  `
    ................................
    ..........................i.....
    .........................jhi....
    ........................ihhhi...
    .........................ihhhi..
    ........................jhhhhhh.
    .......................jhhhghg..
    ......................jhhhg.h...
    .....................jhhhg......
    ..........eedddd...cjhhhgg......
    .......eeeeedddddcccihhg........
    ......eeeeeddddddccciggb........
    .....eeeeeeddddddccccbb.........
    ....eeeeeeddddddcccccb..........
    ....eeeeddddddddccccbb..........
    ...eeedddndddddcccccbbb.........
    ...dddddddndddcccccbbbb.........
    ...ddddddddddccccccbbbb.........
    ...ddddddddcccccccbbbbb.........
    ...dddddddcccccccbbbbbb.........
    ...ddddnccccccccbbbbbbb.........
    ....ccccccccccnnbbbbbb..........
    ....cccccccccbbbbbbbbb..........
    .....cccccbbbbbbbbbbb...........
    ......bbbbbbnbbbbbbb............
    .......bbbbbbbbbbbb.............
    ..........bbbbbb................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const CLAW = icon(
  'icon-claw',
  { b: 'shell.1', c: 'shell.2', d: 'shell.3', e: 'shell.4' },
  `
    ................................
    ................................
    ................................
    ........................cc......
    .......................cccc.....
    ......................cccccb....
    .....................ccccbb.....
    ....................ccccbb......
    ...................dcccbb.......
    .............eedddddcccbb.......
    ...........eeeddddddcccb........
    ..........eeeddddddcccc.........
    .........eeedddddddcccc.........
    .........eddddddddccccb.....b...
    ........dddddddddbccccbb..bbb...
    ........ddddddddcccccbbbbbbbb...
    ........ddddddccccccbbbbbbbbb...
    ........ddddcccccccbbbbbbbbb....
    .........ccccbccccbbbbbbbb......
    .........cccccccbbbbbbbbb.......
    ........ccccccbbbbbbbbb.........
    .......bbccbbbbbbbbbb...........
    ......bbbbbbbbbbbbb.............
    .....bbbbbbb....................
    ....bbbbbbb.....................
    ...bbbbbbb......................
    ..bbbbbbb.......................
    ..bbbbbb........................
    ..bbbbb.........................
    ..bbbb..........................
    ................................
    ................................
`,
);

export const FISH = icon(
  'icon-fish',
  {
    b: 'spray.1',
    c: 'spray.2',
    d: 'spray.3',
    e: 'spray.4',
    g: 'spray.1',
    h: 'spray.2',
    i: 'spray.3',
    j: 'spray.4',
    k: 'ink.0',
    o: 'ink.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................i...............
    ...............jhi..............
    .............jihhg..............
    ............igggggh.............
    ........eeddddddddcc.........b..
    ......eeeddddddddccccc......bb..
    .....eddddbdddddccccccb....bbb..
    ....ddodddbddddccccccbbb..bbb...
    ...ddddkddbddccccdccbbbbbbbbb...
    ...dddddddbcccccccbbbbbbbbbbb...
    ...ddddcccbccccccbbbbbbbbbbbb...
    ...cccccccbccccdbbbdbbbbbbbbb...
    ....ccccccbcbbbbbbbbbbbb..bbb...
    .....ccccbbbbbbbbbbbbbb....bbb..
    ......bbbbbbbbbbbbbbbb......bb..
    ........bbbbbbiiiibb.........b..
    ...............ihg..............
    ................h...............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const EEL = icon(
  'icon-eel',
  {
    b: 'furBog.1',
    c: 'furBog.2',
    d: 'furBog.3',
    e: 'furBog.4',
    h: 'furBog.2',
    i: 'furBog.3',
    k: 'ink.0',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...................iih..........
    .................ieddddi........
    ................ddcccccdc.......
    ................idcccccbid......
    ...............edcccccccdcd.....
    ..............ebccccbcccccb.....
    ..............didccb.dccccb.....
    ..eddd.......ebdccb...dccccd....
    .ebkdcd......didccb....dccccd...
    .dcdccb.....dcdccb.....dccccb...
    .dccccb.....idccb.......dccccd..
    .dccccb....ddcccb........dccccd.
    .dccccb...didccb.........dccccb.
    ..dcccbih.iecccb..........dcccb.
    ...dcccddddcccb...........dcccb.
    ...dccccccccccb............dbbb.
    ....dccccccccb..................
    .....dccccccb...................
    ......dbbbbb....................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

/**
 * A pike, the band's fish (decision 139): long, the jaw to the left and the
 * fins set back by the tail, in oilskin's olive so that cooked and burnt are
 * recolours of it as they are of the fish and the eel.
 */
export const PIKE = icon(
  'icon-pike',
  {
    b: 'oilskin.1',
    c: 'oilskin.2',
    d: 'oilskin.3',
    e: 'oilskin.4',
    k: 'ink.0',
    o: 'ink.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .......................dc.......
    ....................ddddc.......
    ..................eddddcc...dd..
    ..........eeeeeeedddddddc..ddd..
    .....eeeeeedddddddddddddddcdddd.
    ..eeeekodddddddddddddddddccdddd.
    .edddddddddddddddddccccccccccdd.
    ..eddcccccccccccccccccccbbbcccb.
    ....dccccccccccccccbbbbbbbb.bbb.
    ......cccccccccbbbbbbbbbb...bbb.
    ........ccbbbbbbbbbbbbb......bb.
    ..........bbbbcbbbbbb........b..
    ............bbbcbb..............
    ..............bb................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const HIDE = icon(
  'icon-hide',
  { b: 'furBog.1', c: 'furBog.2', d: 'furBog.3', e: 'furBog.4' },
  `
    ................................
    ...............ed...............
    ...............db...............
    .edd...........db............ed.
    .dccdd.........db..........edcb.
    .dccccd..edddddccdddddd...ecccb.
    ..dbcccddccccccccccccccdddcccbb.
    ....dcccccccccccccccccccccccb...
    .....dcccccccccbccccccccccbb....
    ......dccccccccccccccccccb......
    ......dccccccccccccccccccb......
    ......dccccdccccbccccccccb......
    ......dccccccccccccccdcccb......
    ......dccccccccccccccccccb......
    ......dccccccccbcccccccccb......
    ......dccccccccccccccccccb......
    .......dccccccccccccccccb.......
    .......dccccccccbcccccccb.......
    .......dccccccccccccccccb.......
    .......dccccdcccccccccccb.......
    .......dcccccccbccccdcccb.......
    .......dccccccccccccccccb.......
    .......dccccccccccccccccb.......
    .......dccccccccbccccccccd......
    .....edcccccccccccccccccccdd....
    ....eccccccccccccccccccbccccd...
    ....dccbbbbbbbbbbbbbbbb.dbccb...
    ..edccb...................dccdd.
    .eccccb...................dcccb.
    .dccbb.....................dbcb.
    .dbb.........................db.
    ................................
`,
);

export const SHELL = icon(
  'icon-shell',
  { b: 'shellCave.1', c: 'shellCave.2', d: 'shellCave.3' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ............dddddddc............
    ..........ddddbdbdbccc..........
    ........dddddbddbdcbcccc........
    .......ddddddbddbccbccccb.......
    ......ddddddbdddbcccbcccbb......
    .....dddddddbdccbcccbccbbbb.....
    ....ddddddddbcccbcccbcbbbbbb....
    ....dddddddbccccbccccbbbbbbb....
    ....dddddccbccccbcccbbbbbbbb....
    ...ddddcccbcccccbccbbbbbbbbbb...
    ...cccccccbcccccbbbbbbbbbbbbb...
    ...ccccccbccccccbbbbbbbbbbbbb...
    ...ccccccbccccbbbbbbbbbbbbbbb...
    ...ccccccbccbbbbbbbbbbbbbbbbb...
    ...cccccbbbbbbbbbbbbbbbbbbbbb...
    ....bbbbbbbbbbbbbbbbbbbbbbbbb...
    .....b..b..b..b..b..b..b..b.....
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const LOG = icon(
  'icon-log',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'wood.1',
    h: 'wood.2',
    i: 'wood.3',
    j: 'wood.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ......ggggd.....................
    .....ghhhhgddd..................
    ....ghhhhhhgdcddd...............
    ....hhiiiihhdccccddd............
    ...ghhiiiibhgdccccccddd.........
    ...ghiijjibhgdbccccccccddd......
    ...ghiijjibhgdbcccccccccccd.....
    ...ghiijjiibgdbcccbccccccdb.....
    ...ghiijjiibgdcbccbcccbccb......
    ...ghhiiiihbbccbcccbccbcccd.....
    ....hhiiiihhbccbcccbcccbcb......
    ....ghhhhhhgbcccbccbcccbcb......
    .....ghhhhgebcccbccbbccbcb......
    ......ggggdcbcccbcccbccbb.......
    ...........dbbccbcccbcccb.......
    .............bbbbbccbcccb.......
    .................bbbcbccb.......
    ....................dbbb.b......
    .......................c.b......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const ORE = icon(
  'icon-ore',
  {
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    g: 'ore.1',
    i: 'ore.3',
    j: 'ore.4',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ..................edd...........
    .............eddddcccd..........
    ...........bdcccccccccd.........
    ..........ebcccccccccccd........
    .........eccbccccccbbcccd.......
    .........dccbcccccbjidcccd......
    ........ecccbcccccbigdccccd.....
    ........dbbccbcccccddcccccb.....
    .......ebjidccbcccccccccbbbb....
    ......ecbigdccbccccccccbjid.....
    ......dccddcccbcccccbbbbigd.....
    ......dccccccccbcbbbccccddcd....
    .....ecccccccccbbccccccccccb....
    .....dcccccccccbcccccccccccb....
    .....dccbbccccbcccccccbbcccb....
    ....eccbjidcccbccccccbjidccb....
    ....dccbigdccbbccccccbigdccb....
    .....dccddccbjidccccccddccb.....
    ......dcccccbigdcccccccccb......
    .......dcccccbdcccbbccccb.......
    ........dccccbcccbjidccb........
    .........dccbccccbigdcb.........
    ..........dbbbbbbbddbb..........
    ............b...................
    ................................
    ................................
    ................................
    ................................
`,
);

export const COAL = icon(
  'icon-coal',
  { b: 'oreCoal.1', c: 'oreCoal.2', d: 'oreCoal.3', e: 'oreCoal.4' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    .................edddd..........
    ............bddddcccccd.........
    ...........ebccccccccccd........
    ..........eccbccccccecccd.......
    ..........dccbcccccccccccd......
    .........eeccbccccccccccccd.....
    ........ecccccbccccccccccccd....
    ........dccccccbcccccccccccb....
    .......ecccccccbcccccccccccb....
    ......eccccccccbcccccccccbbbb...
    ......dcccccccccbcccbbbbbccb....
    .....eccccccccccbbbbcccccccb....
    .....dccecccccccbcccccccccb.....
    .....dcccccccccbccccccccecb.....
    ....eccccccccccbccccccccccb.....
    ....dccccccccebcccccccccccb.....
    .....dcccccccbbcccccccccccb.....
    ......dccccccbcccccccccccb......
    .......dccccbcccccccccccb.......
    ........dcccbcccccccccbb........
    .........dbbcccccccccb..........
    ...........bbbbbbcccb...........
    .................dbb............
    ................................
    ................................
    ................................
    ................................
`,
);

export const RUNE_STONE = icon(
  'icon-rune-stone',
  { b: 'slate.1', c: 'slate.2', d: 'slate.3', e: 'slate.4', i: 'purple.3', j: 'purple.4' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ............eeeedddd............
    ..........eeeeeedddddc..........
    .........eeeeeeedddddcc.........
    ........eeeeeeeedddddccc........
    .......eeeeeeieedddddcccc.......
    ......eeeeeejiiiiddddccccb......
    ......eeeeeeeiddiddddccccb......
    ......eeeeeeeidddiiicccccb......
    .....deeeeeedidddddiicccbbb.....
    .....deeeeeddiddiiicccccbbb.....
    .....ddddddddidiidccccccbbb.....
    .....ddddddddiiddccccccbbbb.....
    .....dddddddjiidccccccbbbbb.....
    .....ddddddddiicccccccbbbbb.....
    .....cdddddddicicccccbbbbbb.....
    ......ddddddciccicccbbbbbb......
    ......cccccccicccicbbbbbbb......
    ......cccccccicccbibbbbbbb......
    .......cccccciccbbibbbbbb.......
    ........cccccibbbbbibbbb........
    .........bbbbbbbbbbbbbb.........
    ..........bbbbbbbbbbbb..........
    ............bbbbbbbb............
    ................................
    ................................
    ................................
    ................................
`,
);

export const BAR = icon(
  'icon-bar',
  { b: 'tier.1', c: 'tier.2', d: 'tier.3', e: 'tier.4' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...........eeeeeeeeeeeeeeeeee...
    ..........eddddddddddddddddb....
    .........eddddddddddddddddbb....
    ........eddddddddddddddddbbb....
    .......eedddddddddddddddbbbb....
    ......eddddddddddddddddbbbbb....
    .....eddddddddddddddddbbbbbb....
    ....eccccccccccccccccbbbbbbb....
    ....cccccccccccccccccbbbbbb.....
    ....cccccccccdcccccccbbbbb......
    ....ccccdccccccccccccbbbb.......
    ....cccccccccccccdcccbbb........
    ....cccccccccccccccccbb.........
    ....cccccccccccccccccb..........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
`,
);

export const KEY = icon(
  'icon-key',
  { b: 'metal.1', c: 'metal.2', d: 'metal.3', e: 'metal.4' },
  `
    ................................
    ................................
    ................................
    ......eddddd....................
    .....eccccccd...................
    ....eccbbbbccd..................
    ...eccb....dccd.................
    ...dcb......dcb.................
    ...dcb......dcb.................
    ...dcb......dcb.................
    ...dcb......dcb.................
    ...dccd....eccb.................
    ....dccddddcccb.................
    .....dcccccccccd................
    ......dbbbbbbcccd...............
    .............dcccd..............
    ..............dcccd.............
    ...............dcccd............
    ................dcccd...........
    .................dcccd..........
    ..................dcccd.........
    ...................dcccd........
    ...................dccccd.......
    .................edcbbcccd......
    .................dcb..dcccd.....
    ................ecb....dcccd....
    ................db.....dcccb....
    .....................edcbbbb....
    .....................dcb........
    ....................ecb.........
    ....................db..........
    ................................
`,
);

export const ARROW = icon(
  'icon-arrow',
  {
    b: 'thatch.1',
    c: 'thatch.2',
    d: 'thatch.3',
    e: 'thatch.4',
    g: 'wood.1',
    h: 'wood.2',
    i: 'wood.3',
    j: 'wood.4',
    l: 'bone.1',
    m: 'bone.2',
    n: 'bone.3',
  },
  `
    ................................
    ................................
    ............................i...
    ..........................jig...
    .......................jiihg....
    ......................ihhhhg....
    .......................ihhhg....
    .......................dihhg....
    ......................eccig.....
    .....................ecb..h.....
    ....................ecb.........
    ...................ecb..........
    ..................ecb...........
    .................ecb............
    ................ecb.............
    ...............ecb..............
    ..............ecb...............
    .............ecb................
    ............ecb.................
    ...........ecb..................
    ..........ecb...................
    .n.......ecb....................
    ..n.....ecb.....................
    ...nnnndcb......................
    ....nmmnc.......................
    .....nmmn.......................
    ....ednml.......................
    ....db.nl.......................
    ........m.......................
    .........n......................
    ..........n.....................
    ................................
`,
);

export const SHAFTS = icon(
  'icon-shafts',
  {
    b: 'thatch.1',
    c: 'thatch.2',
    d: 'thatch.3',
    e: 'thatch.4',
    g: 'leather.1',
    h: 'leather.2',
    i: 'leather.3',
    j: 'leather.4',
  },
  `
    ................................
    ................................
    ....................ed..........
    ...................ecb..........
    ..................ecb...........
    .................ecb...ed.......
    ................ecb...ecb.......
    ...............ecb...ecb........
    ..............ecb...ecb...ed....
    .............ecb...ecb...ecb....
    ............ecb...ecb...ecb.....
    ...........ecb...ecb...ecb......
    ........jidcb...ecb...ecb.......
    ........ihic...ecb...ecb........
    ........dihi..ecb...ecb.........
    .......eccihidcb...ecb..........
    ......ecb..ihic...ecb...........
    .....ecb...dihi..ecb............
    ....ecb...eccihidcb.............
    ...ecb...ecb..ihic..............
    ..ecb...ecb...dihi..............
    .ecb...ecb...eccihi.............
    .db...ecb...ecb..ig.............
    .c...ecb...ecb..................
    ....ecb...ecb...................
    ...ecb...ecb....................
    ...db...ecb.....................
    .......ecb......................
    ......ecb.......................
    ......db........................
    ................................
    ................................
`,
);

export const ARROWHEADS = icon(
  'icon-arrowheads',
  { b: 'tier.1', c: 'tier.2', d: 'tier.3', e: 'tier.4' },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ...................ed...........
    ...................db...........
    ..................eccd..........
    ..................dcccd.........
    .................eccccb.........
    ................ecbccbcd........
    ................db.db.db........
    ...............d...db...d.......
    ....................c...........
    ................................
    ........ed......................
    ........db......................
    .......eccd.....................
    .......dcccd....................
    ......eccccb.........ed.........
    .....ecbccbcd........db.........
    .....db.db.db.......eccd........
    ....d...db...d......dcccd.......
    .........c.........eccccb.......
    ..................ecbccbcd......
    ..................db.db.db......
    .................d...db...d.....
    ......................c.........
    ................................
    ................................
    ................................
    ................................
`,
);

export const SICKLE = icon(
  'icon-sickle',
  {
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    q: 'wood.1',
    r: 'wood.2',
    s: 'wood.3',
    t: 'wood.4',
    w: 'gold.2',
    x: 'gold.3',
  },
  `
  ................................
  ................................
  ................................
  .................e..............
  .............eeeccceee..........
  ...........eecccccccccee........
  ..........eeccc.....ccced.......
  .........eecc.........ccdd......
  .........ecc...........ccd......
  ........ecc.............ccd.....
  ........ecc.............bbd.....
  ........ec...............bd.....
  ........cc...............bb.....
  .......ecc................bd....
  ........cc................b.....
  ........ec................b.....
  ........ecc...............b.....
  ........ecc...............d.....
  .........wx.....................
  ........wx......................
  ........tsr.....................
  .......tsr......................
  ......tsr.......................
  ......tsr.......................
  .....tsr........................
  ....tsr.........................
  ...tsr..........................
  ...tsr..........................
  ..tsr...........................
  .tsr............................
  .qq.............................
  ................................
`,
);

export const HERB = icon(
  'icon-herb',
  {
    a: 'nature.0',
    b: 'nature.1',
    c: 'nature.2',
    d: 'nature.3',
    e: 'nature.4',
    p: 'bone.2',
    q: 'bone.3',
    r: 'bone.4',
    s: 'linen.2',
    t: 'linen.3',
  },
  `
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..qrr..qrr..qrr.qrr..qrr..qrr...
  ..rqq..rqq..rqq.rqq..rqq..rqq...
  ..eppbe.ppe..pp..pp.c.ppc.dpp...
  ...d.cbd.cbd.cb..cbd.cbd..cb....
  ....ccb.ccb.ccb..cc..cc..cc.....
  ......cb..cb.cb..cb..cb.cb......
  ....e.dbe.de.db..db.db.cdbc.....
  ......dcbdcbd.cb.cbdcbdcbd......
  ......c.b.ccbccb.cc.cc.cc.......
  ........cb.cb.cbcb.cb.cb........
  .........dbdb.dbdb.dbdb.........
  .........cb.cbcbcb.cbcb.........
  ..........cbcbcbcbcbcb..........
  ..........c.cbcbcbcbcb..........
  ...........dbddbddbdb...........
  ............cccbcccb............
  ............ccbccccb............
  ............ttttssss............
  ............ssssssss............
  .............ababab.............
  .............bababa.............
  .............ababab.............
  .............bababa.............
  ................................
`,
);

export const POTION = icon(
  'icon-potion',
  {
    G: 'spray.1',
    H: 'spray.2',
    I: 'spray.3',
    J: 'spray.4',
    k: 'nature.0',
    l: 'nature.1',
    m: 'nature.2',
    n: 'nature.3',
    o: 'nature.4',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
  },
  `
  ................................
  ................................
  ................................
  ..............zyyxx.............
  ..............zyyxx.............
  ..............zyyxx.............
  ..............zyyxx.............
  .............JJGGGHH............
  ..............JGGGH.............
  ..............JGGGH.............
  ..............JGGGH.............
  ..............JGGGH.............
  .............IIIIIII............
  .............JJJJJJI............
  ...........JJGGGGGGGII..........
  ..........JJGGGGGGGGGII.........
  ..........JGJGGGGGGGGGI.........
  .........JGJGGGGGGGGGGGI........
  .........JoJoooooooooooH........
  .........JnnnnnnmmmmmmmH........
  ........JJnnnnnmmmmmmmlHH.......
  .........JnnnnmmmmmmlllH........
  .........JnnmmmmmmmllllH........
  .........InmmmmmmmlllllH........
  ..........ImmmmmllllllH.........
  ..........IImmmlllllkHH.........
  ...........IImlllllkHH..........
  .............IHHHHHH............
  ................H...............
  ................................
  ................................
  ................................
`,
);

/** A cart bell on its leather strap, the brass dulled with the road (F1's first keepsake). */
export const BELL = icon(
  'icon-bell',
  {
    a: 'leather.1',
    s: 'leather.2',
    t: 'leather.3',
    b: 'gold.0',
    c: 'gold.1',
    d: 'gold.2',
    e: 'gold.3',
    f: 'gold.4',
    k: 'metal.1',
    m: 'metal.3',
  },
  `
    ................................
    ................................
    ................................
    ..............tsss..............
    .............ts..sa.............
    .............t....a.............
    .............s....a.............
    ..............saaa..............
    ..............eddc..............
    .............feddcc.............
    ............feeddccb............
    ............feeddccb............
    ...........ffeeddcccb...........
    ...........ffeeddcccb...........
    ...........ffeeddcccb...........
    ...........ffeedddccb...........
    ..........dffeeddddccb..........
    ..........dffeeddddccb..........
    ..........dffeeddddccb..........
    .........dffeeeddddcccb.........
    .........dfeeeedddddccb.........
    ........ddffeeeddddcccbb........
    .......cccccccccccccccbbb.......
    ......ddffeeeeddddddcccccb......
    ......cdddddddddcccccccbbb......
    .......bbbbbbbbbbbbbbbbbb.......
    ...............mk...............
    ...............kk...............
    ................................
    ................................
    ................................
    ................................
`,
);

/** A seal pressed in red wax, a lamp cut in it, on two ribbon tails (F1's second keepsake). */
export const SEAL = icon(
  'icon-seal',
  {
    q: 'crimson.1',
    r: 'crimson.1',
    s: 'crimson.2',
    t: 'crimson.3',
    u: 'crimson.4',
    v: 'crimson.0',
    m: 'blue.2',
    n: 'blue.3',
  },
  `
    ................................
    ................................
    ................................
    ................................
    ................................
    ............qqqqqqqq............
    ..........qqquuuuutqqq..........
    .........qquuuuuuttttrr.........
    ........qquuuuuvvtttttrr........
    .......qquuuuuvvvvtttttrr.......
    .......quuuuuuvvvvttttssr.......
    ......qquuuuuttvvttttsssrr......
    ......quuuuutqqqqqqtsssssr......
    ......quuuutqqqqqqqqsssssr......
    ......quuuttvvvvvvvvssssrr......
    ......quutttqqqqqqqqsssrrr......
    ......qutttttqqqqqqsssrrrr......
    ......qtttttttqqqqsssrrrrr......
    ......qqttttttsqqsssrrrrrr......
    .......qtttttqqqqqqrrrrrr.......
    .......qrtttsvvvvvvrrrrrr.......
    ........rrtssssssrrrrrrr........
    .........rrsssssrrrrrrr.........
    ..........rrrssrrrrrrr..........
    .........mnnrrrrrrrrmmn.........
    .........mnn........mmn.........
    ..........mnn......mmn..........
    ..........mnn......mmn..........
    ...........mnn....mmn...........
    ...........mnn....mmn...........
    ............mnn..mmn............
    ................................
`,
);
