import { grid, type SpriteDef } from '../format';
import type { ColourRef } from '../palette';

/**
 * The small pictures that stand beside a word (B8, decision 111): each tab's
 * and each of the menu's, and the coin beside a purse. Sixteen pixels, a line
 * of the world's font high, so a tab is its picture over its word.
 *
 * Painted by a generator out of shapes shaded by the style guide's light and
 * pasted in as the pictures it made, as the trees were (decision 109).
 */

function icon(id: string, legend: Readonly<Record<string, ColourRef>>, rows: string): SpriteDef {
  return { id, kind: 'icon', width: 16, height: 16, legend, animations: { still: [grid(rows)] } };
}

export const BUST = icon(
  'mark-bust',
  {
    b: 'metal.1',
    c: 'metal.2',
    d: 'metal.3',
    e: 'metal.4',
    h: 'skin.2',
    i: 'skin.3',
    l: 'blue.1',
    m: 'blue.2',
    n: 'blue.3',
    o: 'blue.4',
  },
  `
    ................
    ................
    ......eedd......
    .....eeeddc.....
    .....eeddcc.....
    ....ddddccbb....
    .....diccib.....
    .....ciccib.....
    ......hcch......
    .....onnnnn.....
    ....ommmmmmn....
    ...ommmmmmmmn...
    ...nmmmmmmmml...
    ..ommmmmmmmmmn..
    ..nlllllllllll..
    ................
`,
);

export const SACK = icon(
  'mark-sack',
  {
    b: 'ochre.1',
    c: 'ochre.2',
    d: 'ochre.3',
    e: 'ochre.4',
    g: 'leather.1',
    i: 'leather.3',
    j: 'leather.4',
  },
  `
    ................
    ................
    ......dddd......
    .......ddd......
    .......dd.......
    .....jiiiii.....
    ....eigggggc....
    ...eeddddcccb...
    ..ddddddccccbb..
    ..dddddccccbbb..
    ..dddcccccbbbb..
    ..cccccccbbbbb..
    ...ccccbbbbbb...
    ....bbbbbbbb....
    .....bbbbbb.....
    ................
`,
);

export const SCROLL = icon(
  'mark-scroll',
  {
    b: 'bone.1',
    c: 'bone.2',
    d: 'bone.3',
    e: 'bone.4',
    g: 'bone.1',
    i: 'bone.3',
    j: 'bone.4',
    l: 'red.1',
    m: 'red.2',
    n: 'red.3',
    o: 'red.4',
  },
  `
    ................
    ................
    ..jiiiiiiiiiii..
    ..iggggggggggg..
    ...eddddddddd...
    ...dcbbbbbbcb...
    ...dccccccccb...
    ...dcbbbbbbcb...
    ...dccccccbbb...
    ...dcbbbbbonc...
    ...dccccbommn...
    ...dbbbbbnmml...
    ..jiiiiiiinlji..
    ..igggggggiigg..
    ................
    ................
`,
);

export const HOURGLASS = icon(
  'mark-hourglass',
  {
    b: 'wood.1',
    d: 'wood.3',
    e: 'wood.4',
    g: 'spray.1',
    h: 'spray.2',
    i: 'spray.3',
    j: 'spray.4',
    l: 'yellow.1',
    m: 'yellow.2',
    n: 'yellow.3',
    o: 'yellow.4',
  },
  `
    ................
    ...eddddddddd...
    ...dbbbbbbbbb...
    ...d.iiiiih.d...
    ...d..nnnm..d...
    ...d..inli..d...
    ...d...nl...d...
    ...d...ji...d...
    ...d...ig...d...
    ...d...in...d...
    ...d..igih..d...
    ...d..onnn..d...
    ...d.nllllm.d...
    ...dddddddddb...
    ...dbbbbbbbbb...
    ................
`,
);

export const CHEST = icon(
  'mark-chest',
  {
    b: 'wood.1',
    c: 'wood.2',
    d: 'wood.3',
    e: 'wood.4',
    g: 'wood.1',
    h: 'wood.2',
    i: 'wood.3',
    j: 'wood.4',
    m: 'gold.2',
    n: 'gold.3',
    q: 'metal.1',
    s: 'metal.3',
    t: 'metal.4',
  },
  `
    ................
    ................
    ................
    ....njiiiiin....
    ...inihhhhgn....
    ...inihhhhgni...
    ..ignigggggnh...
    ..nnmnmtsnnmnm..
    ..ednedsqedned..
    ..dbndbsqdbndb..
    ..dbndcddcbndb..
    ..dbndccccbndb..
    ..dbndccccbndb..
    ..dbmdbbbbbmdb..
    ................
    ................
`,
);

export const MAP = icon(
  'mark-map',
  { b: 'bone.1', c: 'bone.2', d: 'bone.3', e: 'bone.4', g: 'leather.1', n: 'red.3' },
  `
    ................
    ................
    ...edbdd....ed..
    .edccbccddbdcb..
    .dcccbccccbbcb..
    .dcccbbbccbncn..
    .dcccbggdcbcnd..
    .dccbgedgdbndn..
    .dcbgbcbgggdcd..
    .dbgebccddbgdb..
    .dgecbccccbdcb..
    .ddccbccccbccb..
    .dcbbbbbccbcbb..
    .db..b..dbbb....
    ..........b.....
    ................
`,
);

export const TROPHY = icon(
  'mark-trophy',
  { b: 'gold.1', c: 'gold.2', d: 'gold.3', g: 'wood.1', h: 'wood.2', i: 'wood.3', j: 'wood.4' },
  `
    ................
    ................
    ...dddddcccb....
    .ddddddccccb.bb.
    .dd.ddccccbb.bb.
    .dd.dccccbb..bb.
    ....ccccbbb.....
    .....ccbbb......
    ......bbb.......
    .......bb.......
    .......bb.......
    .......bb.......
    ....jiiiiiii....
    ....ihhhhhhg....
    ....iggggggg....
    ................
`,
);

export const BOOK = icon(
  'mark-book',
  {
    b: 'crimson.1',
    c: 'crimson.2',
    d: 'crimson.3',
    e: 'crimson.4',
    g: 'bone.1',
    h: 'bone.2',
    i: 'bone.3',
    j: 'bone.4',
    l: 'crimson.1',
    n: 'crimson.3',
    o: 'crimson.4',
    q: 'gold.1',
    s: 'gold.3',
    t: 'gold.4',
  },
  `
    ................
    ................
    ..oneddddddddd..
    ..nldccccccccb..
    ..nldcbbbbbccb..
    ..nldbtssssdcb..
    ..nldbscccsdcb..
    ..nldbscccsdcb..
    ..nldbssssqdcb..
    ..nldcdddddccb..
    ..nldccccccccb..
    ..nldbbbbbbbbb..
    ..nljiiiiiiiii..
    ..nlihhhhhhhhg..
    ..nliggggggggg..
    ................
`,
);

// The Whispers journal's (D2): a candle lit, which is what a rumour is told by
// and what the old kingdom kept.
export const CANDLE = icon(
  'mark-candle',
  {
    a: 'fire.4',
    b: 'fire.3',
    c: 'fire.2',
    k: 'ink.1',
    e: 'bone.4',
    f: 'bone.3',
    g: 'bone.2',
    l: 'metal.1',
    m: 'metal.2',
    n: 'metal.3',
  },
  `
    ................
    .......b........
    ......bab.......
    ......aab.......
    ......bac.......
    .......k........
    .....eeffg......
    .....effgg......
    .....effgg......
    .....effgg......
    .....effgg......
    .....effgg......
    ...nnmmmmmml....
    ..nmmmmmmmmmml..
    ...llllllllll...
    ................
`,
);

export const SWORDS = icon(
  'mark-swords',
  { b: 'metal.1', d: 'metal.3', e: 'metal.4', i: 'leather.3', n: 'gold.3' },
  `
    ................
    ................
    ................
    ...e........e...
    ....d......d....
    .....d....d.....
    ......d..d......
    .......ed.......
    .......db.......
    ......d..d......
    ...n.d....d.n...
    ....i......i....
    ...i.n....n.i...
    ..i..........i..
    ................
    ................
`,
);

export const COG = icon(
  'mark-cog',
  { b: 'metal.1', c: 'metal.2', d: 'metal.3', e: 'metal.4', f: 'ink.0' },
  `
    ................
    ......eed.......
    ...ee.eed.dc....
    ..eeeeeddddcc...
    ..eeeeeddddcc...
    ...eedddddcc....
    .eeeddfffccccb..
    .dddddfffcccbb..
    .dddddfffccbbb..
    ...ddcccccbb....
    ..cccccccbbbb...
    ..ccccccbbbbb...
    ...cc.bbb.bb....
    ......bbb.......
    ................
    ................
`,
);

export const COIN = icon(
  'mark-coin',
  { b: 'gold.1', c: 'gold.2', d: 'gold.3', e: 'gold.4' },
  `
    ................
    ................
    ......eedd......
    ....eeebbddc....
    ...eebbedbbcc...
    ...ebeeddddbc...
    ..eebeddddcbcb..
    ..dbdddddcccbb..
    ..dbddddcccbbb..
    ..ddbddccccbbb..
    ...cbccccbbbb...
    ...ccbbcbbbbb...
    ....bbbbbbbb....
    ......bbbb......
    ................
    ................
`,
);
