import { grid, type SpriteDef } from '../format';

/**
 * Props drawn for real ahead of B6, where a placeholder crate was not only
 * unfinished but misleading: a signpost is how a zone says where its exits
 * go, and a crate says nothing (decision 104).
 */

/** A post with two boards nailed across it, pointing either way, their letters cut in. */
export const SIGNPOST: SpriteDef = {
  id: 'signpost',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    k: 'ink.0',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..............yyy...............
  .............xxxxx..............
  ..............zyx...............
  ..............zyx...............
  .....wwwwwwwwwwwwwwwwwwww.......
  .....wzzzzzzzzzzzzzzzzzzzz......
  .....wyyyyyyyyyyyyyyyyyyyyy.....
  .....wyywywyyywywyyywywyyyy.....
  .....wxxxxxxxxxxxxxxxxxxxx......
  .....vvvvvvvvvvvvvvvvvvvv.......
  ..............zyx...............
  ..............zyx...............
  .......wwwwwwwwwwwwwwwwwwww.....
  ......zzzzzzzzzzzzzzzzzzzzw.....
  .....yyyyyyyyyyyyyyyyyyyyyw.....
  .....yyywywyyywywyyywywyyyw.....
  ......xxxxxxxxxxxxxxxxxxxxw.....
  .......vvvvvvvvvvvvvvvvvvvv.....
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............zyx...............
  ..............yyx...............
  ............kwyyxwk.............
  ................................
  ................................
      `),
    ],
  },
};
