import { grid, type SpriteDef } from '../format';

/**
 * What the zones hide (decision 117), each drawn as the thing it is and never
 * named over it: a secret is found by walking up to it, so it has to be seen
 * to be wondered about, and nothing but its drawing says it is there.
 */

/**
 * The Lamp Stone, in Lampton's crossroads: a waymarker the first carters took
 * for a lamp-post, its empty iron cage on top, letters worn into it that
 * nobody in the town can read, and a notice pinned where anyone will see it.
 */
export const LAMP_STONE: SpriteDef = {
  id: 'lamp-stone',
  kind: 'prop',
  width: 32,
  height: 64,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    o: 'metal.3',
    p: 'linen.3',
    q: 'linen.2',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...............on...............
  ...............nn...............
  ...............nn...............
  ............nnnnnnnn............
  ...........oooooooooo...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........mmmmmmmmmm...........
  ..........deeeeeeeeeee..........
  ..........dccccccccccb..........
  ..........dccccccccccb..........
  ..........dbbbbbbbbbbb..........
  ............ddccccbb............
  ............ddccccbb............
  ............ddccccbb............
  ............ddccccbb............
  ............bbbbbbbb............
  ............eeeeeeee............
  ............ddccccbb............
  ............ddacccbb............
  ............ddccacbb............
  ............ddccccbb............
  ............ddcaccbb............
  ............ddcccabb............
  ............ddccccbb............
  ............ddacccbb............
  ............ddccccbb............
  ............ddccacbb............
  ............ddccccbb............
  ............ddcaccbb............
  ............ddccccbb............
  ............ddcccabb............
  ............ddccccbb............
  ............ddccccbb............
  ............bbbbbbbb............
  ............eeeeeeee............
  ............dppkpqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dqqqqqbb............
  ............ddccccbb............
  .........dddddddddddddd.........
  .........dccccccccccccb.........
  .........dccccccccccccb.........
  .........dccccccccccccb.........
  .........bbbbbbbbbbbbbb.........
  ................................
  ................................
      `),
    ],
  },
};

/** The hatch round the back of the Wet Boot: planks bound in iron, flat in the ground, a ring to lift it by. */
export const CELLAR_HATCH: SpriteDef = {
  id: 'cellar-hatch',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......vvvvvvvvvvvvvvvvvvvv......
  ......vyyyyyyyyyyyyyyyyyyv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxmmmmmmmmmmmmmmmmxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxnxxxxwxxxv......
  ......vxxxxwxxxnknxxxwxxxv......
  ......vxxxxwxxxxnxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxmmmmmmmmmmmmmmmmxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vwwwwwwwwwwwwwwwwwwv......
  ......vvvvvvvvvvvvvvvvvvvv......
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/** The warden's niche at the nearest Candle's foot: dressed stone, and a dark arch where a light was kept. */
export const WARDEN_NICHE: SpriteDef = {
  id: 'warden-niche',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......ddeeeeeeeeeeeeeeeeee......
  ......ddccccccccccccccccbb......
  ......ddccccccccccccccccbb......
  ......ddccccccccccccccccbb......
  ......ddcccccckkkkccccccbb......
  ......ddccccckkkkkkcccccbb......
  ......ddbbbbbkkkkkkbbbbbbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddbbbbakkkkkkabbbbbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddbbbbakkkkkkabbbbbb......
  ......ddcccddddddddddcccbb......
  ......ddccccccccccccccccbb......
  ......bbbbbbbbbbbbbbbbbbbb......
  ................................
  ................................
      `),
    ],
  },
};
