import { grid, type SpriteDef } from '../format';

/**
 * What the zones hide (decision 117), each drawn as the thing it is and never
 * named over it: a secret is found by walking up to it, so it has to be seen
 * to be wondered about, and nothing but its drawing says it is there.
 */

/**
 * The Lamp Stone, in Lampton's crossroads: a waymarker the first carters took
 * for a lamp-post, its empty iron cage on top, letters worn into it that
 * nobody in the town can read, and a notice pinned where anyone will see it.
 */
export const LAMP_STONE: SpriteDef = {
  id: 'lamp-stone',
  kind: 'prop',
  width: 32,
  height: 64,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    o: 'metal.3',
    p: 'linen.3',
    q: 'linen.2',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...............on...............
  ...............nn...............
  ...............nn...............
  ............nnnnnnnn............
  ...........oooooooooo...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........n..m..m..n...........
  ...........mmmmmmmmmm...........
  ..........deeeeeeeeeee..........
  ..........dccccccccccb..........
  ..........dccccccccccb..........
  ..........dbbbbbbbbbbb..........
  ............ddccccbb............
  ............ddccccbb............
  ............ddccccbb............
  ............ddccccbb............
  ............bbbbbbbb............
  ............eeeeeeee............
  ............ddccccbb............
  ............ddacccbb............
  ............ddccacbb............
  ............ddccccbb............
  ............ddcaccbb............
  ............ddcccabb............
  ............ddccccbb............
  ............ddacccbb............
  ............ddccccbb............
  ............ddccacbb............
  ............ddccccbb............
  ............ddcaccbb............
  ............ddccccbb............
  ............ddcccabb............
  ............ddccccbb............
  ............ddccccbb............
  ............bbbbbbbb............
  ............eeeeeeee............
  ............dppkpqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dppppqbb............
  ............dqqqqqbb............
  ............ddccccbb............
  .........dddddddddddddd.........
  .........dccccccccccccb.........
  .........dccccccccccccb.........
  .........dccccccccccccb.........
  .........bbbbbbbbbbbbbb.........
  ................................
  ................................
      `),
    ],
  },
};

/** The hatch round the back of the Wet Boot: planks bound in iron, flat in the ground, a ring to lift it by. */
export const CELLAR_HATCH: SpriteDef = {
  id: 'cellar-hatch',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......vvvvvvvvvvvvvvvvvvvv......
  ......vyyyyyyyyyyyyyyyyyyv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxmmmmmmmmmmmmmmmmxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxnxxxxwxxxv......
  ......vxxxxwxxxnknxxxwxxxv......
  ......vxxxxwxxxxnxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxmmmmmmmmmmmmmmmmxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vxxxxwxxxxwxxxxwxxxv......
  ......vwwwwwwwwwwwwwwwwwwv......
  ......vvvvvvvvvvvvvvvvvvvv......
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/** The warden's niche at the nearest Candle's foot: dressed stone, and a dark arch where a light was kept. */
export const WARDEN_NICHE: SpriteDef = {
  id: 'warden-niche',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......ddeeeeeeeeeeeeeeeeee......
  ......ddccccccccccccccccbb......
  ......ddccccccccccccccccbb......
  ......ddccccccccccccccccbb......
  ......ddcccccckkkkccccccbb......
  ......ddccccckkkkkkcccccbb......
  ......ddbbbbbkkkkkkbbbbbbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddbbbbakkkkkkabbbbbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddccccakkkkkkaccccbb......
  ......ddbbbbakkkkkkabbbbbb......
  ......ddcccddddddddddcccbb......
  ......ddccccccccccccccccbb......
  ......bbbbbbbbbbbbbbbbbbbb......
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The broken cell behind the New Cut's face: a slab of dressed stone set in the
 * rock with a niche for a lantern in it, empty, a line cut over it in letters
 * nobody can read, and the crack the third blast put through it, its chips
 * lying on the floor.
 */
export const BROKEN_CELL: SpriteDef = {
  id: 'broken-cell',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ......eeeeeeeeeeeeeeeeeeeeee....
  ......dcccccccccccccccckccbb....
  ......dcacaacacaacaacckccccb....
  ......dcccccccccccccccccckcb....
  ......dbbbbbbbbbbbbbbbbbbkbb....
  ......dccccccckkkkcccccccckb....
  ......dcccccckkkkkkccccccccb....
  ......dccccckkkkkkkkcccccccb....
  ......dcccccakkkkkkkkacccccb....
  ......dbbbbbakkkkkkkkabbbbbb....
  ......dcccccakkkkkkkkacccccb....
  ......dcccccakkkkkkkkacccccb....
  ......dcccccakeddddddacccccb....
  ......dcccccakkkkkkkkacccccb....
  ......dbbbbbabbbbbbbbabbbbbb....
  ......dccccccccccccccccckccb....
  ......dcccccccccccccccckkccb....
  ......bbbbbbbbbbbbbbbbbkbbbb....
  ................................
  ................................
  .........ec.....................
  ........ecbb.............ec.....
  ........dcb.............ecbb....
  ........................dcb.....
  ................................
  ..............ec................
  .............ecb................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The lamp niche in the back wall of Redrag Camp's hall: an arch with the soot
 * of six hundred years of nothing over it, the iron the lamp hung from, and a
 * strip of Company red tucked in where somebody hides their purse.
 */
export const LAMP_NICHE: SpriteDef = {
  id: 'lamp-niche',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    k: 'ink.0',
    l: 'ink.1',
    m: 'metal.1',
    n: 'metal.2',
    r: 'red.1',
    s: 'red.2',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ......eee.eeeeeeeee..eeee.......
  .....decccdcccccccccbeccccb.....
  .....dccccccccclllccccccccb.....
  .....dccccccccllklllcccccccb....
  .....dbbbbbbbbllkkllbbbbbbbb....
  .....dcccccccllkkkkllcccccccb...
  .....dccccccclknnnnklcccccccb...
  .....dccccccakkkmmkkkacccccb....
  .....dcccccakkkkmmkkkkaccccb....
  .....dbbbbbakkkkkkkkkkabbbbb....
  .....dcccccakkkkkkkkkkaccccb....
  .....dcccccakkkrsrrkkkaccccb....
  .....dcccccakkrsrrsrkkaccccb....
  .....dcccccakdddddddddaccccb....
  .....dbbbbbabbbbrsbbbbabbbbb....
  .....dcccccccccccrscccccccccb...
  .....dcccccccccccccsccccccccb...
  .....bbbbbbbbbbbbbbbbbbbbbbbb...
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The strongbox at the end of the Cellar's low passage: the Company's, off the
 * pay-cart Hollis drove off the road, iron-bound oak with its lid thrown back,
 * the red seal on its front broken, and gold in it with a face on the gold.
 * Some has spilled.
 */
export const STRONGBOX: SpriteDef = {
  id: 'strongbox',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    g: 'gold.2',
    h: 'gold.3',
    i: 'gold.4',
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    r: 'red.1',
    s: 'red.2',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .......vvvvvvvvvvvvvvvvvv.......
  .......vnnnnnnnnnnnnnnnnv.......
  .......vwwwwmwwwwwwmwwwwv.......
  .......vwwwwmwwwwwwmwwwwv.......
  .......vwxwwmwwxwwwmwwxwv.......
  .......vwwwwmwwwwwwmwwwwv.......
  ......vvvvvvvvvvvvvvvvvvvv......
  ......vkkkhkkkkgkkkkkhkkkv......
  ......vkgkkkihkkkgkkhgkkkv......
  ......vnnnnnnnnnnnnnnnnnnv......
  ......vyyyymyyyyyyyymyyyyv......
  ......vxxxxmxxxxxxxxmxxxxv......
  ......vxxxxmxxxrsxxxmxxxxv......
  ......vxxxxmxxxskrxxmxxxxv......
  ......vxxxxmxxxxrxxxmxxxxv......
  ......vnnnnnnnnnnnnnnnnnnv......
  ......vwwwwmwwwwwwwwmwwwwv......
  ......vwwwwmwwwwwwwwmwwwwv......
  ......vvvvvvvvvvvvvvvvvvvv......
  ................................
  .....hg.................ig......
  ......................hg........
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The frieze along the barrow's gallery: Veymar's coast cut in relief in a
 * panel of dressed stone, the sea-lights standing out of the waves a mile apart
 * with their lamps inlaid in gold and burning, the first picture of the kingdom
 * as it was. A crack runs down through it from the top, and the coin the
 * fenfolk left at its foot is still there.
 */
export const SEA_LIGHT_FRIEZE: SpriteDef = {
  id: 'sea-light-frieze',
  kind: 'prop',
  width: 64,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    g: 'gold.2',
    h: 'gold.3',
    i: 'gold.4',
    k: 'ink.0',
  },
  animations: {
    still: [
      grid(`
  ................................................................
  ................................................................
  ..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..
  ..dccccccccccccccccccccccccccccccccccccccccccccckccccccccccccb..
  ..dcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkbbbbbbbbbbbcb..
  ..dcbbbbbhbbbbbbbbhbbbbbbbbhbbbbbbbbhbbbbbbbbhbbbkbbbbhbbbbbcb..
  ..dcbbbbhihbbbbbbhihbbbbbbhihbbbbbbhihbbbbbbhihbbkbbbhihbbbbcb..
  ..dcbbbbedabbbbbbedabbbbbbedabbbbbbedabbbbbbedabbbkbbedabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbkbbecabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbkbecabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbcb..
  ..dcbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbbbecabbbbcb..
  ..dcbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbcb..
  ..dcbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbcb..
  ..dcbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbbdbbbbdbcb..
  ..dcdbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbddbbbbbbdcb..
  ..dccccccccccccccccccccccccccccccccccccccccccccccccccccccccccb..
  ..bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb..
  ................................................................
  ................................................................
  ............................................gh..................
  ....................hg..........................................
  ..................................ihg...........................
  ...........................hg...................................
  ................................................................
  ................................................................
  ................................................................
  ................................................................
  ................................................................
  ................................................................
      `),
    ],
  },
};

/**
 * The shrine under the Old Mill Road's millpond, where the elves said goodbye to
 * Veymar: a slab cut with a leaf, seen through the water from the bank, the
 * village's coin in the silt round it. A mark rather than a prop, as a fishing
 * spot's rings are: it is the water's surface with the stone showing through,
 * not outlined, and the light on it drifting on the water's clock.
 */
export const POND_SHRINE: SpriteDef = {
  id: 'pond-shrine',
  kind: 'mark',
  width: 32,
  height: 32,
  legend: {
    b: 'water.2',
    c: 'water.3',
    d: 'water.4',
    g: 'gold.2',
    h: 'gold.3',
  },
  animations: {
    loop: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........cccdcccdcc...........
  .........cccccbbbbccccc.........
  .......ccccccbbbbbbcccccc.......
  ......ccccccbbdbccbbcccccc......
  .....cccccccbddbcccbccccccc.....
  .....ccccccbbbdbccbbbcccccc.....
  ....cccccccbddbbcbccbccccccc....
  ....cccccccbdddbccccbccccccc....
  ....cccccccbbddbcccbbccccccc....
  ....cccccccbdbdbccbcbccccccc....
  ....bccccccbddbbcbccbccccccb....
  ....bccccccbdddbccccbccccccb....
  ....bccccccbbddbcccbbccccccb....
  ....bbcccccbbbdbccbbbcccccbb....
  .....bccccccbdbbcbcbccccccb.....
  .....bbcccccbbdbccbbcccccbb.....
  ......bbcccccbbbbbbcccccbb......
  .......bbcccccbbbbcccccbb.......
  .....hg..bbccccccccccbb.........
  ...........bbbbbbbbbb....hg.....
  ................................
  .........h..........g...........
  ................................
  ................................
  ................................
  ................................
      `),
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........cccccccccc...........
  .........cccccbbbbccccc.........
  .......ccccccbbbbbbcccccc.......
  ......ccccccbbdbccbbcccccc......
  .....cccccccbddbcccbccccccc.....
  .....cdcccdbbbdbccdbbcdcccd.....
  ....cdcccdcbddbbcdccbdcccdcc....
  ....cccccccbdddbccccbccccccc....
  ....cccccccbbddbcccbbccccccc....
  ....cccccccbdbdbccbcbccccccc....
  ....bccccccbddbbcbccbccccccb....
  ....bccccccbdddbccccbccccccb....
  ....bccccccbbddbcccbbccccccb....
  ....bbcccccbbbdbccbbbcccccbb....
  .....bccccccbdbbcbcbccccccb.....
  .....bbcccccbbdbccbbcccccbb.....
  ......bbcccccbbbbbbcccccbb......
  .......bbcccccbbbbcccccbb.......
  .....hg..bbccccccccccbb.........
  ...........bbbbbbbbbb....hg.....
  ................................
  .........h..........g...........
  ................................
  ................................
  ................................
  ................................
      `),
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........cccccccccc...........
  .........cccccbbbbccccc.........
  .......ccccccbbbbbbcccccc.......
  ......ccccccbbdbccbbcccccc......
  .....cccccccbddbcccbccccccc.....
  .....ccccccbbbdbccbbbcccccc.....
  ....cccccccbddbbcbccbccccccc....
  ....cccccccbdddbccccbccccccc....
  ....cccccccbbddbcccbbccccccc....
  ....cccccccbdbdbccbcbccccccc....
  ....bccccccbddbbcbccbccccccb....
  ....bdcccdcbdddbcdccbdcccdcb....
  ....dcccdccbdddbdccbdcccdccb....
  ....bbcccccbbbdbccbbbcccccbb....
  .....bccccccbdbbcbcbccccccb.....
  .....bbcccccbbdbccbbcccccbb.....
  ......bbcccccbbbbbbcccccbb......
  .......bbcccccbbbbcccccbb.......
  .....hg..bbccccccccccbb.........
  ...........bbbbbbbbbb....hg.....
  ................................
  .........h..........g...........
  ................................
  ................................
  ................................
  ................................
      `),
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...........cccccccccc...........
  .........cccccbbbbccccc.........
  .......ccccccbbbbbbcccccc.......
  ......ccccccbbdbccbbcccccc......
  .....cccccccbddbcccbccccccc.....
  .....ccccccbbbdbccbbbcccccc.....
  ....cccccccbddbbcbccbccccccc....
  ....cccccccbdddbccccbccccccc....
  ....cccccccbbddbcccbbccccccc....
  ....cccccccbdbdbccbcbccccccc....
  ....bccccccbddbbcbccbccccccb....
  ....bccccccbdddbccccbccccccb....
  ....bccccccbbddbcccbbccccccb....
  ....bbcccccbbbdbccbbbcccccbb....
  .....bccccccbdbbcbcbccccccb.....
  .....bbcccccbbdbccbbcccccbb.....
  ......bbcccccbbbbbbcccccbb......
  .......bdcccdcbbdbccdccbd.......
  .....hg..bbdcccdcccdcbb.........
  ...........bbbbbbbbbb....hg.....
  ................................
  .........h..........g...........
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The first charter's ledger in the Old Mill, open on a writing desk against
 * the west wall: two pages of a hand gone small with the cold, a candle burnt
 * down and never lit again, and the mill's last takings in a box at its foot.
 */
export const CHARTER_LEDGER: SpriteDef = {
  id: 'charter-ledger',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    g: 'gold.2',
    h: 'gold.3',
    i: 'ink.2',
    k: 'ink.0',
    m: 'metal.1',
    n: 'metal.2',
    o: 'bone.4',
    p: 'linen.4',
    q: 'linen.3',
    r: 'linen.2',
    s: 'leather.1',
    t: 'leather.2',
    u: 'bone.2',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .........................k......
  .........................ou.....
  .........................ou.....
  .........................ou.....
  .........zzzzzzzzzzzzzzzzouz....
  .........yysssssskssssssmnnm....
  .........yyspppppkqqqqqsyyyy....
  .........yyspiiirkqiiiqsyyyy....
  .........yyspppppkqqqqqsyyyy....
  .........yyspiirpkqiirqsyyyy....
  .........yyspppppkqqqqqsyyyy....
  .........yytttttttttttttyyyy....
  .........zzzzzzzzzzzzzzzzzzz....
  .........wxxxxxxxxxxxxxxxxxx....
  .........wxxwwwwwwxxwwwwwwxx....
  .........wxxwxxxxwxxwxxxxwxx....
  .........wxxwxxxxwxxwxxxxwxx....
  .........wxxwwwwwwxxwwwwwwxx....
  .........wxxxxxxxxxxxxxxxxxx....
  .........vvvvvvvvvvvvvvvvvvv....
  ..........vv.......yyyyyyvv.....
  ...................wwhwww.......
  ...................vvvvvv.hg....
  ................................
  ................................
      `),
    ],
  },
};

/**
 * The keystone of the Veymari bridge at Greyford, lying in the ford by the pier
 * it fell from, its carved face up: a wedge of dressed stone with a lamp burning
 * cut into it, cracked across the corner it landed on, and a carter's coin
 * beside it for luck.
 */
export const BRIDGE_KEYSTONE: SpriteDef = {
  id: 'bridge-keystone',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    a: 'masonry.0',
    b: 'masonry.1',
    c: 'masonry.2',
    d: 'masonry.3',
    e: 'masonry.4',
    g: 'gold.2',
    h: 'gold.3',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ....eeeeeeeeeeeeeeeeeeeeeeee....
  ....ddddddddddddddddddddbddb....
  .....dccccccccccccccccccbcb.....
  .....dccccccccccaccccccbccb.....
  ......dcccbccccaeacccbcbcb......
  ......dccccbcccaeaccbcccbb......
  ......dcccccccaeeeaccccccb......
  .......dcbbcccaedeaccbbcb.......
  .......dcccccccadaccccccb.......
  .......dcccccaaaaaaaccccb.......
  ........dcccccabbbaccccb........
  ........dccccccaaacccccb........
  .........dccccccccccccb.........
  .........dccccccccccccb.........
  .........bbbbbbbbbbbbbb.........
  ..........aaaaaaaaaaaa..........
  ...........................hg...
  .....hg.........................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};

/**
 * What waits in the fettler's back room: a chest of grave goods with its lock
 * broken and its lid thrown back, a ring set on the lid's edge, and beside it a
 * lantern with a crack down its pane and nothing in it.
 */
export const BACK_ROOM: SpriteDef = {
  id: 'back-room',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    e: 'metal.4',
    g: 'gold.2',
    h: 'gold.3',
    i: 'gold.4',
    k: 'ink.0',
    l: 'ink.2',
    m: 'metal.1',
    n: 'metal.2',
    p: 'linen.4',
    q: 'linen.2',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
  },
  animations: {
    still: [
      grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ..............ii................
  .............h..h...............
  ..............hh................
  .....yyyyyyyyyyyyyyy............
  .....nnnnnnnnnnnnnnn....nn......
  .....wwwwwwwwwwwwwww...m..m.....
  .....vvvvvvvvvvvvvvv...nnnn.....
  ......kkkkkkkkkkkkk...meellm....
  ......khhkkqqqpkhkk...melllm....
  ......khhgkqqqqkghk...mllklm....
  ......kkkkkkkkkkkkk...mlkllm....
  .....wyyyyyyyyyyyyyw..mlkllm....
  .....wxxxxxxxxxxxxxw..mllklm....
  .....wxxxxxxxxxxxxxw..mlllkm....
  .....wxxxxxmmmxxxxxw..mllklm....
  .....nnnnnnmkmnnnnnn..mllllm....
  .....wxxxxxmmmxxxxxw..mllllm....
  .....wxxxxxxxxxxxxxw..nnnnnn....
  .....wxxxxxxxxxxxxxw.mmmmmmmm...
  .....wxxxxxxxxxxxxxw............
  .....wvvvvvvvvvvvvvw............
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
      `),
    ],
  },
};
