import { grid, type SpriteDef } from '../format';

/**
 * What a maker works at (decision 109): the three stations a zone came with,
 * each a silhouette of its own at a glance, and the fire
 * the player lights. Drawn in shared ramps, since a forge is the same stone
 * and iron in any light, and standing on the ground as a prop does.
 */

const FORGE_LOOP_0 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ......................j.........
  ................................
  .......................i........
  ............EEEEEEEEEEEEEEEEEE..
  ............EDBBBBBBBBBBBBBBDB..
  ............EDhhlhhgigiiilggDB..
  ....QQQQQQQQQQQhhghiiligjihiDB..
  ..QPPPPPPPPPPPPOhilhigjgjijhDB..
  ...NOOOOPPPOOONDDDDDDDDDDDDDDB..
  ......NNOOONNMAAAAAAAAAAAAAAAA..
  ........NOONCCCCCCBCCCCCCBCCBB..
  ........NOONMCCCCCBCCCCCCBCCBB..
  ......MNOOOONMBBBBAAAAAAABBBBB..
  ......MNNNNNNMCCCAAgggggAACBBB..
  .....yzzzyyxCBCCCAghhihhgACBBB..
  .....yyyxxxwCBCCCAghiiihgACBBB..
  .....xyxxwxwBBBBBAghhihhgABBBB..
  .....xxwxxwwCCCBCAAAAAAAAACCBB..
  .....xyxwxwvCCCBCCCCCCBCCCCCBB..
  .....wxxwxwvCCCBCCCCCCBCCCCCBB..
  ....vvwwvwvvBBBBBBBBBBBBBBBBBB..
  ............AAAAAAAAAAAAAAAAAA..
  ................................
  ................................
`);

const FORGE_LOOP_1 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..................j.............
  ................................
  ................................
  ................................
  ................................
  ............EEEEEEEEEEEEEEEEEE..
  ............EDBBBBBBBBBBBBBBDB..
  ............EDihlhhgihijilggDB..
  ....QQQQQQQQQQQgghhihlhhihhjDB..
  ..QPPPPPPPPPPPPOhhlhjgjhjijhDB..
  ...NOOOOPPPOOONDDDDDDDDDDDDDDB..
  ......NNOOONNMAAAAAAAAAAAAAAAA..
  ........NOONCCCCCCBCCCCCCBCCBB..
  ........NOONMCCCCCBCCCCCCBCCBB..
  ......MNOOOONMBBBBAAAAAAABBBBB..
  ......MNNNNNNMCCCAAgggggAACBBB..
  .....yzzzyyxCBCCCAghhihhgACBBB..
  .....yyyxxxwCBCCCAghijihgACBBB..
  .....xyxxwxwBBBBBAghhihhgABBBB..
  .....xxwxxwwCCCBCAAAAAAAAACCBB..
  .....xyxwxwvCCCBCCCCCCBCCCCCBB..
  .....wxxwxwvCCCBCCCCCCBCCCCCBB..
  ....vvwwvwvvBBBBBBBBBBBBBBBBBB..
  ............AAAAAAAAAAAAAAAAAA..
  ................................
  ................................
`);

const FORGE_LOOP_2 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  .........................j......
  ................................
  ..........................i.....
  ................................
  ................................
  ................................
  ............EEEEEEEEEEEEEEEEEE..
  ............EDBBBBBBBBBBBBBBDB..
  ............EDiglhhgjhiiilggDB..
  ....QQQQQQQQQQQhghhihlhhiigiDB..
  ..QPPPPPPPPPPPPOihlhjgjgjijgDB..
  ...NOOOOPPPOOONDDDDDDDDDDDDDDB..
  ......NNOOONNMAAAAAAAAAAAAAAAA..
  ........NOONCCCCCCBCCCCCCBCCBB..
  ........NOONMCCCCCBCCCCCCBCCBB..
  ......MNOOOONMBBBBAAAAAAABBBBB..
  ......MNNNNNNMCCCAAgggggAACBBB..
  .....yzzzyyxCBCCCAghhihhgACBBB..
  .....yyyxxxwCBCCCAghiiihgACBBB..
  .....xyxxwxwBBBBBAghhihhgABBBB..
  .....xxwxxwwCCCBCAAAAAAAAACCBB..
  .....xyxwxwvCCCBCCCCCCBCCCCCBB..
  .....wxxwxwvCCCBCCCCCCBCCCCCBB..
  ....vvwwvwvvBBBBBBBBBBBBBBBBBB..
  ............AAAAAAAAAAAAAAAAAA..
  ................................
  ................................
`);

const FORGE_LOOP_3 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ....................j...........
  ................................
  ............EEEEEEEEEEEEEEEEEE..
  ............EDBBBBBBBBBBBBBBDB..
  ............EDihlhhgjhhjilggDB..
  ....QQQQQQQQQQQghhhihlhhjhgiDB..
  ..QPPPPPPPPPPPPOhilhjgjgjijhDB..
  ...NOOOOPPPOOONDDDDDDDDDDDDDDB..
  ......NNOOONNMAAAAAAAAAAAAAAAA..
  ........NOONCCCCCCBCCCCCCBCCBB..
  ........NOONMCCCCCBCCCCCCBCCBB..
  ......MNOOOONMBBBBAAAAAAABBBBB..
  ......MNNNNNNMCCCAAgggggAACBBB..
  .....yzzzyyxCBCCCAghhihhgACBBB..
  .....yyyxxxwCBCCCAghihihgACBBB..
  .....xyxxwxwBBBBBAghhihhgABBBB..
  .....xxwxxwwCCCBCAAAAAAAAACCBB..
  .....xyxwxwvCCCBCCCCCCBCCCCCBB..
  .....wxxwxwvCCCBCCCCCCBCCCCCBB..
  ....vvwwvwvvBBBBBBBBBBBBBBBBBB..
  ............AAAAAAAAAAAAAAAAAA..
  ................................
  ................................
`);

/**
 * The forge: a block of dressed stone with a bed of coals in its top and its
 * mouth glowing, and an anvil on a stump in front. It loops, since the coals
 * are always lit: a few embers brighten and dim, and a spark goes up.
 */
export const FORGE: SpriteDef = {
  id: 'forge',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    A: 'masonry.0',
    B: 'masonry.1',
    C: 'masonry.2',
    D: 'masonry.3',
    E: 'masonry.4',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    M: 'metal.0',
    N: 'metal.1',
    O: 'metal.2',
    P: 'metal.3',
    Q: 'metal.4',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    l: 'ink.1',
  },
  animations: { loop: [FORGE_LOOP_0, FORGE_LOOP_1, FORGE_LOOP_2, FORGE_LOOP_3] },
};

const TANNERY_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ....yyyyyyyyyyyyyyyyyyyyyyyy....
  ....xxxxxxxxxxxxxxxxxxxxxxxx....
  ....vvvvvvvvvvvvvvvvvvvvvvvv....
  .....xw........ut........xw.....
  .....xw...333333333333...xw.....
  .....xut.34444433333333stxw.....
  .....xw.3444433333332222.xw.....
  .....xw.3443333333322222.xw.....
  .....xw.3433333333222222.xw.....
  .....xw.3333333332222222.xw.....
  .....xut.33333332222222stxw.....
  .....xw..333333222222221.xw.....
  .....xw..233332222222221.xw.....
  .....xw..233222222222211.xw.....
  .....xw..222222222222211.xw.....
  .....xut222222222222211stxw.....
  .....xw.2222222222222111.xw.....
  .....xw.2222222222221111.xw.....
  .....xw..22222222221111..xw.....
  .....xw..12222222111111..xw.....
  .....xut..111111111111.stxw.....
  .....xw....1111111111....xw.....
  .....xw..................xw.....
  .....xw..................xw.....
  .....xyyyyyyyyyyyyyyyyyyyxw.....
  ....yzzzzzzyyyyyyyyyyyyyyxw.....
  ...yzyooooopppppooooooooxyx.....
  ...yyoopqqqpppppooooooooxxx.....
  ...xyoopppoooooooooooooxxxw.....
  ....xxxxxxxxxxxxxxxxxxxxxww.....
  ....yyxwxxowxxxwxxxwxxxwwww.....
  ....PONNNNoNNNNNNNNNNNNNMMM.....
  ....yyxwxxxwxxxwxxxwxxxwwww.....
  ....yyxwxxxwxxxwxxxwxxxwwww.....
  ....yyxwxxxwxxxwxxxwxxxwwww.....
  ....yyxwxxxwxxxwxxxwxxxwwww.....
  ....PONNNNNNNNNNNNNNNNNNMMM.....
  ....yyxwxxxwxxxwxxxwxxxwwww.....
  ....yvvvvvvvvvvvvvvvvvvvvvw.....
  ................................
  ................................
`);

/**
 * The tannery: a vat of liquor with a hide laced to a frame behind it, a
 * wooden thing full of liquid with something soft hanging off it, the forge's
 * opposite at a glance.
 */
export const TANNERY: SpriteDef = {
  id: 'tannery',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    M: 'metal.0',
    N: 'metal.1',
    O: 'metal.2',
    P: 'metal.3',
    '1': 'leather.0',
    '2': 'leather.1',
    '3': 'leather.2',
    '4': 'leather.3',
    o: 'ochre.1',
    p: 'ochre.2',
    q: 'ochre.3',
    s: 'linen.2',
    t: 'linen.3',
    u: 'linen.4',
  },
  animations: { still: [TANNERY_STILL] },
};

const FLETCHING_BENCH_STILL = grid(`
  ................................
  ................................
  ................................
  .........................x......
  ........................zw......
  ........................yw......
  ........................yw.t....
  ........................yw.t....
  ........................yw.t....
  ........................zw.t....
  .........................yw.t...
  .........................yw.t...
  .........................yw.t...
  .........................yw.t...
  .........................zw.t...
  .........................yw.t...
  .........................yw.t...
  .........................yw.t...
  .........................yw.t...
  .........................zw.t...
  ....................ccc..yw.t...
  ......QPuuuuuuuuuuuuccc..yw.t...
  .......NssssssssssssHHH..yw.t...
  ......QPuuuuuuuuuuuuHHH.bcw.t...
  .......Nssssssssssssccc.cbc.t...
  ......QPuuuuuuuuuuuuccc..bywt...
  ...zzzzNssssssssssssszbzzzzzz...
  ...yyyyyyxPPPPwwwyyyyyyxyyyyy...
  ...yyyyyyxyyyyyyxyyyyyyxyyyyy...
  ...yyyyyyyyyyyyyyyyyyyyyyyyyy...
  ...xxxxxxxxxxxxxxxxxxxxxxxxxx...
  ...wwwwwwwwwwwwwwwwwwwwwwwwww...
  ...vvvvvvvvvvvvvvvvvvvvvvvvvv...
  .....xw...............xw..yw....
  .....xw...............xw........
  ....xw.x.............xw.x.......
  ....xw.x.............xw.x.......
  ....xw..x...........xw..x.......
  ....xw..xw..........xw..xw......
  ....xw..xw..........xw..xw......
  ....vv..vv..........vv..vv......
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
`);

/**
 * The fletcher's bench: a plank on splayed trestles with shafts laid on it,
 * their heads one way and their fletching the other, a knife and a twist of
 * feathers, and a strung bow stood behind it, taller than anything else here.
 */
export const FLETCHING_BENCH: SpriteDef = {
  id: 'fletching-bench',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    N: 'metal.1',
    P: 'metal.3',
    Q: 'metal.4',
    s: 'linen.2',
    t: 'linen.3',
    u: 'linen.4',
    b: 'bone.3',
    c: 'bone.4',
    H: 'crimson.2',
  },
  animations: { still: [FLETCHING_BENCH_STILL] },
};

const CAMPFIRE_LOOP_0 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...............h................
  ..............hh................
  ..............hih...............
  .............hiih..h............
  ............hhijih.hh...........
  ...........hhijjjihhh...........
  ...........hijjjjjiih...........
  ..........hhijjjjjjih...........
  ..........hiijjjjjiihh..........
  ..........hiijjjjjjiih..........
  ..........ghiiijjjiihg..........
  ...........ghiiiiiihg...........
  .......Uyyyy.DD....DD...T.......
  ........xxxxyyyB..DCCxxxDD......
  .......DCCB.ixxyyyxxxwwwCCB.....
  .......BBBA....xxhyyy..BBBA.....
  .....DD.....xxiwwwxxxyyy...DD...
  ....DCCTxxxxwww.i..h.xxxT.DCCB..
  ....BBBAwwww...........DD.BBBA..
  ........DCCB....DD....DCCB......
  ........BBBA...DCCB...BBBA......
  ................................
  ................................
`);

const CAMPFIRE_LOOP_1 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  .................h..............
  ................hh..............
  ..........h....hih..............
  ..........hh...hiih.............
  ..........hih.hhijhh............
  ...........hihhijjih............
  ...........hiiijjjiih...........
  ..........hhiijjjjjih...........
  ..........hiijjjjjjihh..........
  ..........hiijjjjjjiih..........
  ..........ghiiijjjiihg..........
  ...........ghiiiiiihg...........
  .......Uyyyy.DD....DD...T.......
  ........xxxxyyyB..DCCxxxDD......
  .......DCCB.hxxyyyxxxwwwCCB.....
  .......BBBA....xxiyyy..BBBA.....
  .....DD.....xxhwwwxxxyyy...DD...
  ....DCCTxxxxwww.h..i.xxxT.DCCB..
  ....BBBAwwww...........DD.BBBA..
  ........DCCB....DD....DCCB......
  ........BBBA...DCCB...BBBA......
  ................................
  ................................
`);

const CAMPFIRE_LOOP_2 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................h...............
  ...............hh...............
  ...............hih..............
  ..........h...hiih..............
  ..........hh.hhijih.............
  ...........hhhijjjih.h..........
  ...........hiijjjjjhhh..........
  ..........hhiijjjjjiih..........
  ..........hiijjjjjjiih..........
  ..........hiijjjjjjiih..........
  ..........ghiiijjjiihg..........
  ...........ghiiiiiihg...........
  .......Uyyyy.DD....DD...T.......
  ........xxxxyyyB..DCCxxxDD......
  .......DCCB.ixxyyyxxxwwwCCB.....
  .......BBBA....xxhyyy..BBBA.....
  .....DD.....xxiwwwxxxyyy...DD...
  ....DCCTxxxxwww.i..h.xxxT.DCCB..
  ....BBBAwwww...........DD.BBBA..
  ........DCCB....DD....DCCB......
  ........BBBA...DCCB...BBBA......
  ................................
  ................................
`);

const CAMPFIRE_LOOP_3 = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..............h.................
  ..............hh................
  .............hih....h...........
  .............hiih...hh..........
  ............hhijihh.hh..........
  ...........hhijjjiihh...........
  ...........hijjjjjiih...........
  ..........hhijjjjjjih...........
  ..........hiijjjjjiihh..........
  ..........hiijjjjjjiih..........
  ..........ghiiijjjiihg..........
  ...........ghiiiiiihg...........
  .......Uyyyy.DD....DD...T.......
  ........xxxxyyyB..DCCxxxDD......
  .......DCCB.hxxyyyxxxwwwCCB.....
  .......BBBA....xxiyyy..BBBA.....
  .....DD.....xxhwwwxxxyyy...DD...
  ....DCCTxxxxwww.h..i.xxxT.DCCB..
  ....BBBAwwww...........DD.BBBA..
  ........DCCB....DD....DCCB......
  ........BBBA...DCCB...BBBA......
  ................................
  ................................
`);

/** The fire the player lights: a ring of stones, two logs crossed, embers, and a flame over them. */
export const CAMPFIRE: SpriteDef = {
  id: 'campfire',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    A: 'masonry.0',
    B: 'masonry.1',
    C: 'masonry.2',
    D: 'masonry.3',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    T: 'thatch.2',
    U: 'thatch.3',
  },
  animations: { loop: [CAMPFIRE_LOOP_0, CAMPFIRE_LOOP_1, CAMPFIRE_LOOP_2, CAMPFIRE_LOOP_3] },
};

const STILL_STILL = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ...............DDDDDD...........
  ...........E.DBBBBBBBDD.........
  .........EEDDBB......BBD........
  ........EEDDDCC........BD.......
  .......EEDDDCCCC........B.......
  .......EDDDCCCBB........BD......
  .......DDDCCCBBB.........B......
  ........DCCCBBB......xxxxwwwww..
  .........EDDDD.......zvvvvvvvw..
  .......EEDDDDDCC.....zzyyxxwww..
  ......EEDDDDDCCCC....PPPNNNNNN..
  .....EEDDDDDCCCCCC...zzyyxxwww..
  .....EDDDDDCCCCCCB...zzyyxxwww..
  ....EDDDDDCCCCCCBBB..zzyyxxwww..
  ....DDDDDCCCCCCBBBB..zzyyxxwww..
  ....DBDDBCCBCCBBBBB..zzyyxxwww..
  ....DDDCCCCCCBBBBBA..zzyyxxwww..
  ....DDCCCCCCBBBBBAA..zzyyxxwww..
  .....CCCCCCBBBBBAA...zzyyxxwww..
  .....CCCCCBBBBBAAA...zzyyxxwww..
  ......CCCBBBBBAAA....PPPNNNNNN..
  .......CBBBBBAAA.....zzyyxxwww..
  ...ooooooBBBAAnnnnnn.zzyyxxwww..
  ...nmmmmmlmmmmmlmmmk.zzyyxxwww..
  ...nmmmmmlmmmmmlmmmk.zzyyxxwww..
  ...nlllllllllllllllk.zzyyxxwww..
  ...nmmlmkkkkkkkmmmlk.zzyyxxwww..
  ...nmmlmkhhhhhkmmmlDDDzyyxxwww..
  ...nllllhhhhhhhllllC.zzyyxxwww..
  ...nmmmmhhiiihhlmmmk.zzyyxxwww..
  ...nmmmmhhijihhlmmmk.PPPNNNNNN..
  ...nllllhhijihhllllk.zzyyxxwww..
  ...nmmlmggijiggmmmlk.zzyyxxwww..
  ...nkkkkkkkkkkkkkkkk.vvvvvvvvv..
  ................................
  ................................
  ................................
`);

/**
 * The still (version 2 phase E2): a fenfolk pot-still of beaten copper on a
 * stone hearth with a fire in its mouth, its head's long neck running over to
 * a tub of water where the worm cools, and a spout off the tub's foot.
 */
export const STILL: SpriteDef = {
  id: 'still',
  kind: 'prop',
  width: 32,
  height: 48,
  legend: {
    A: 'oreIron.0',
    B: 'oreIron.1',
    C: 'oreIron.2',
    D: 'oreIron.3',
    E: 'oreIron.4',
    k: 'masonry.0',
    l: 'masonry.1',
    m: 'masonry.2',
    n: 'masonry.3',
    o: 'masonry.4',
    v: 'wood.0',
    w: 'wood.1',
    x: 'wood.2',
    y: 'wood.3',
    z: 'wood.4',
    g: 'fire.1',
    h: 'fire.2',
    i: 'fire.3',
    j: 'fire.4',
    N: 'metal.1',
    P: 'metal.3',
  },
  animations: { still: [STILL_STILL] },
};
