import { ORE_VARIANTS, grid, type SpriteDef } from '../format';

/**
 * What a miner works: a boulder of the setting's `rock`, cut into a few planes
 * lit from the top-left, with the ore showing in its seams (decision 109).
 *
 * The ore is drawn in the neutral `ore` ramp and recoloured into the one the
 * vein yields (`ORE_VARIANTS`), the way gear is drawn in `tier`: a vein of tin
 * is `vein@tin`, and step 2 of each ore's ramp is the ore's colour in the bag.
 * A worked-out vein is the same rock with pits where the ore came out, since a
 * node that vanished on the last swing would take with it the thing a player
 * looks at to see whether it is back.
 */

const VEIN_STANDING = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..................nnok..........
  ...........oonomnDnnnokl........
  .......monooooomnnCnnnokllm.....
  ......nmoooEDoomnnnDnnnoklll....
  .....nnnmoDCCBoomnnoCnnookll....
  .....nnnmooBBAoomnoooCollklll...
  .....nnnmooooooooolllDDmmklll...
  ....nnnnomooolllllmmmnCBmklll...
  ....DnnnnolllmmmlmmmmmmCmmklll..
  ....nCnoollmmmmEDmmmmmmmDmklll..
  ....nnDolmmlmmDCCBmmmmnmmCklll..
  .....nnCDmmmmmmBBAmmmmmmmmBlll..
  .....nolCDmmmmmmmmmmmmmmmmklll..
  ....nnnnnBCmnmmmmmmmmnmmmmklll..
  ...onnnnnnoCDDDDDDmmmlDDmmkllk..
  ..nlooonnolmCCDCCDCmmDCCBmkll...
  ..nmllloolmmmBBBBBBBmlBBAklll...
  ..mmmmmllmmmmmmmmmmmmmmmmklll...
  ..mmmmmmmmlmmmmmmmnmlmlmmklll...
  ..mmnmmmmmlmmmmlmmmmmlmmmklkk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkk.....
  ................................
  ................................
  ................................
  ................................
`);

const VEIN_WORKED = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..................nnok..........
  ...........oonomnnnnnokl........
  .......monooooomnnnnnnokllm.....
  ......nmooooooomnnnnnlkkllll....
  .....nnnmooooooomnnonnlknkll....
  .....nnnmooooooomnoooonnlklll...
  .....nnlkklooooooolllllmmklll...
  ....nnnnlknoolllllmmmnmmmklll...
  ....nnnnnnlllmmmlmmmmmmmmmklll..
  ....nnnoollmmmmmlkklmmmmmmklll..
  ....nnnolmmlmmmmmlknmmnmmmklll..
  .....nnolmmmmmmmnnnmmmmmmmklll..
  .....nolllmmmmmmmmmmmmmmmmklll..
  ....nnnnnolmnmmmmmmmmnlkklklll..
  ...onnnnnnolmmmmmmmmmlmlknkllk..
  ..nlooonnolkkllmmmmmmmmnnmkll...
  ..nmllloolmlknmmmmmlmlmmmklll...
  ..mmmmmllmmnnmmmmmmmmmmmmklll...
  ..mmmmmmmmlmmmmmmmnmlmlmmklll...
  ..mmnmmmmmlmmmmlmmmmmlmmmklkk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkk.....
  ................................
  ................................
  ................................
  ................................
`);

const SEAM_STANDING = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..................nnok..........
  ...........oooomnnnnnokl........
  .......mooooEDomnnnnnnoklll.....
  ......nmoooDCCBmnnnnnnnoklll....
  .....nnnmoooBBAomnnmnnnookll....
  .....nnomooooooomnooooollklll...
  .....nnomooooooooolllllmmklll...
  ....CnnAnmooolllllmnmmmmmklll...
  ....ACEDnCCCCCmmmmmmmmmlmmklll..
  ....BBDBCBBAAACCCCmmmmmmmmkllm..
  ....BBBBBBABAEDBBBCEDCmCCmkllm..
  .....BBBBAEDBDBBBBBDCBCBBCCCCl..
  .....BAABBDAABBBABBAABBBBEDABC..
  ....nAnnAAAmmAABAABBBBBBBDBBBB..
  ...onnnnnnolmmmAmmAABAAAABBBBB..
  ..mlooonnolmmmmlmmmmAmBAmABAA...
  ..mmllloolmmmmmmmmlmmnAmmAAll...
  ..mmmmmllmnmmmnmmmmmmmnmmklll...
  ..mmmmmmmmmmmmmmnmlmnmmmmklll...
  ..lmmlmlmmmmmmmmmmmmmmmmmklkk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkk.....
  ................................
  ................................
  ................................
  ................................
`);

const SEAM_WORKED = grid(`
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ................................
  ..................nnok..........
  ...........oooomnnnnnokl........
  .......mooooooomnnnnnnoklll.....
  ......nmooooooomnnnnnnnoklll....
  .....nnnmooooooomnnmnnnookll....
  .....nnomooooooomnooooollklll...
  .....nnomooooooooolllllmmklll...
  ....knnknmooolllllmnmmmmmklll...
  ....lkklnkkkkkmmmmmmmmmlmmklll..
  ....llllklllllkkkkmmmmmmmmkllm..
  ....llllllllllllllkkmkmkkmkllm..
  .....lllllllllllllllklkllkkkkl..
  .....lnnlllnnllllllllllllllllk..
  ....nnnnnnnmmnnlnnllllllllllll..
  ...onnnnnnolmmmnmmnnlnllnlllll..
  ..mlooonnolmmmmlmmmmnmlnmllnn...
  ..mmllloolmmmmmmmmlmmnnmmnnll...
  ..mmmmmllmnmmmnmmmmmmmnmmklll...
  ..mmmmmmmmmmmmmmnmlmnmmmmklll...
  ..lmmlmlmmmmmmmmmmmmmmmmmklkk...
  ..kkkkkkkkkkkkkkkkkkkkkkkkk.....
  ................................
  ................................
  ................................
  ................................
`);

const RICH_VEIN_STANDING = grid(`
  ................................
  ................................
  ................................
  ................................
  ..................nnnok.........
  .............ooCnnnnnnokl.......
  .........oooooomDnnnnnnoklll....
  ......moooEDooomDCnnnnmokllll...
  .....nmooDCCBoomnCBnnmnmoklll...
  ....nnDmooBBAooomnDnnnnoookmll..
  ....nnnCoooooooomnoCooolllklll..
  ....nonmDDooooooooEDCllmmmDDll..
  ....nnonmCColllllDCCBBmmmDCCBl..
  ...nnnnmolBDmmmmmmBBACmmmmBBAl..
  ...nnnoolmnmCmmmmmmlnmDDmmmklll.
  ...nnnnolmmmmCmnmllmmnmCCmmklll.
  ...nnnolmmmmmmBmmmmmmmmmBDDklll.
  ....nnolmmmmnnnEDmmmmmmmmmCClll.
  .....nollmlmmmDCCBmmmmmmlmmBDml.
  ....DnnnolllmmmBBAmmlmlmmmmkmBl.
  ...nnCDnnnnolmmmnmmmmmmmEDmklmk.
  ..onnoDDmnnolmmmmmmmmmnDCCBkll..
  .mlooDCCBnolmmmmmmmmmmmmBBAlll..
  .mmlllBBACDDDDDDDDDDmmmmmmklll..
  .mmmmmmlllCCDCCDCCDCCmmmmmklll..
  .mmmmmmmmmmBBBBBBBBBBBmmmmklll..
  .mmmlmmmmmmmmmmlmmmmmmmmmmklkk..
  .kkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ................................
  ................................
  ................................
  ................................
`);

const RICH_VEIN_WORKED = grid(`
  ................................
  ................................
  ................................
  ................................
  ..................nnnok.........
  .............oomnnnnnnokl.......
  .........oooooomnnnnnnnoklll....
  ......moooonooolkklnnnmokllll...
  .....nmoonooooomlknnnmnmoklll...
  ....nnnmooonoooonnnnnnnoookmll..
  ....nnnlkklooooomnooooolllklll..
  ....nonmlknooooooolllllkklklll..
  ....nnonnnoollllllmmmmmlknklll..
  ...nnnnmolllmmmmmmmlmmmnnmklll..
  ...nnnoolmnmmmmmmmmlnmmmmmmklll.
  ...nnnnolmmmmmmnmllkklmmmmmklll.
  ...nnnolmmmmmmmmmmmlknmmmmmklll.
  ....nnolmmmmnnnmmmmnnmmmmmmklll.
  .....nollmlkklmmmmmmmmmmlmmklml.
  ....nnnnolllknmnmmmmlmlmmmmkmll.
  ...nnnnnnnnnnmmmnmmmmmmmmlmklmk.
  ..onnonnmnnolmmmmmmmmmnnmmmkll..
  .mloolkklnolmmmmmmmmmlkklmklll..
  .mmllllknolmmmlmmmlmmmlknmklll..
  .mmmmmnnllmmmlkklmmmlmnnmmklll..
  .mmmmmmmmmmmmmlknmmmmmmmmmklll..
  .mmmlmmmmmmmmmnnmmmmmmmmmmklkk..
  .kkkkkkkkkkkkkkkkkkkkkkkkkkk....
  ................................
  ................................
  ................................
  ................................
`);

/** A vein: the ore in thin seams and a nugget or two, catching the light. */
export const VEIN: SpriteDef = {
  id: 'vein',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    k: 'rock.0',
    l: 'rock.1',
    m: 'rock.2',
    n: 'rock.3',
    o: 'rock.4',
    A: 'ore.0',
    B: 'ore.1',
    C: 'ore.2',
    D: 'ore.3',
    E: 'ore.4',
  },
  animations: { still: [VEIN_STANDING], spent: [VEIN_WORKED] },
  variants: ORE_VARIANTS,
};

/**
 * A seam: a band of the ore laid right across the stone, glinting, which is
 * how coal lies and what a coal seam is called; in a thin vein, ore nearly as
 * dark as the rock it is in did not show at all.
 */
export const SEAM: SpriteDef = {
  id: 'seam',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    k: 'rock.0',
    l: 'rock.1',
    m: 'rock.2',
    n: 'rock.3',
    o: 'rock.4',
    A: 'ore.0',
    B: 'ore.1',
    C: 'ore.2',
    D: 'ore.3',
    E: 'ore.4',
  },
  animations: { still: [SEAM_STANDING], spent: [SEAM_WORKED] },
  variants: ORE_VARIANTS,
};

/** A rich vein: a bigger stone with the ore running through all of it, worth the level it asks. */
export const RICH_VEIN: SpriteDef = {
  id: 'vein-rich',
  kind: 'prop',
  width: 32,
  height: 32,
  legend: {
    k: 'rock.0',
    l: 'rock.1',
    m: 'rock.2',
    n: 'rock.3',
    o: 'rock.4',
    A: 'ore.0',
    B: 'ore.1',
    C: 'ore.2',
    D: 'ore.3',
    E: 'ore.4',
  },
  animations: { still: [RICH_VEIN_STANDING], spent: [RICH_VEIN_WORKED] },
  variants: ORE_VARIANTS,
};
