import { grid, type Grid, type SpriteDef } from '../format';

/**
 * Wick (D4, `docs/lore/spirit.md`): a kindled soul, a light about the size of a
 * fist, blue-white, floating at the player's shoulder. The blue is the one the
 * card it speaks on is edged in, the arcane ramp's, with a heart of white.
 *
 * Two sprites of the `spirit` kind on its one clock. The first is the light as
 * it is, breathing up and down a pixel with a mote or two loose about it. The
 * second is the light with something to say: brighter, wider, and throwing a
 * glint either side, so a player looking anywhere near the player sees it.
 * Neither is outlined, since light has no edge.
 */

const LEGEND = {
  a: 'arcane.1',
  b: 'arcane.2',
  c: 'arcane.3',
  d: 'arcane.4',
  w: 'metal.4',
} as const;

const GLOW: readonly Grid[] = [
  grid(`
    ................
    ................
    ................
    ................
    .......aa.......
    ...a..abba......
    .....abccba.....
    ....abcddcba....
    ....abdwwdba....
    ....abdwwdba....
    ....abcddcbaa...
    .....abccba.....
    ......abba......
    .......aa.......
    ................
    ................
  `),
  grid(`
    ................
    ................
    ...........a....
    ..a....aa.......
    ......abba......
    .....abccba.....
    ....abcddcba....
    ....abdwwdba....
    ....abdwwdba....
    ....abcddcba....
    .....abccba..a..
    ......abba......
    .......aa.......
    ................
    ................
    ................
  `),
  grid(`
    ................
    ................
    ................
    .......aa...a...
    ......abba......
    .....abccba.....
    ....abcddcba....
    ....abdwwdba....
    ....abdwwdba....
    ....abcddcba....
    ...a.abccba.....
    ......abba......
    .......aa.......
    ................
    ................
    ................
  `),
  grid(`
    ................
    ................
    ................
    ................
    .......aa.......
    ......abba...a..
    .....abccba.....
    ....abcddcba....
    ....abdwwdba....
    ..a.abdwwdba....
    ....abcddcba....
    .....abccba.....
    ....a.abba......
    .......aa.......
    ................
    ................
  `),
];

const CALLING: readonly Grid[] = [
  grid(`
    ................
    ................
    ................
    .......bb.......
    ......abba......
    ...b.abccba.....
    ....abcddcba....
    ...abcdwwdcba...
    ..abcdwwwwdcba..
    ..abcdwwwwdcba..
    ...abcdwwdcba...
    ....abcddcba....
    .....abccba.....
    ......abba......
    .......bb.......
    ................
  `),
  grid(`
    ................
    ................
    .......bb..b....
    ..b...abba......
    .....abccba.....
    ....abcddcba....
    ...abcdwwdcba...
    .abbcdwwwwdcbba.
    .abbcdwwwwdcbba.
    ...abcdwwdcba...
    ....abcddcba.b..
    .....abccba.....
    ......abba......
    .......bb.......
    ................
    ................
  `),
  grid(`
    ................
    ................
    .......bb.......
    ......abba..b...
    .....abccba.....
    ....abcddcba....
    ...abcdwwdcba...
    abbbcdwwwwdcbbba
    abbbcdwwwwdcbbba
    ...abcdwwdcba...
    ...babcddcba....
    .....abccba.....
    ......abba......
    .......bb.......
    ................
    ................
  `),
  grid(`
    ................
    ................
    ................
    .......bb.......
    ......abba......
    .....abccba..b..
    ....abcddcba....
    ...abcdwwdcba...
    .abbcdwwwwdcbba.
    .abbcdwwwwdcbba.
    ...abcdwwdcba...
    ....abcddcba....
    ....babccba.....
    ......abba......
    .......bb.......
    ................
  `),
];

export const WICK: SpriteDef = {
  id: 'wick',
  kind: 'spirit',
  width: 16,
  height: 16,
  legend: LEGEND,
  animations: { loop: GLOW },
};

export const WICK_CALLING: SpriteDef = {
  id: 'wick-calling',
  kind: 'spirit',
  width: 16,
  height: 16,
  legend: LEGEND,
  animations: { loop: CALLING },
};
